// Code generated by MockGen. DO NOT EDIT.
// Source: ../../channel/facade.go
//
// Generated by this command:
//
//	mockgen -source=../../channel/facade.go -destination=mock_channel_facade.go -package=mocks github.com/denkhaus/gollum/pkg/channel ChannelFacadeService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	channel "github.com/denkhaus/gollum/pkg/channel"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockChannelFacadeService is a mock of ChannelFacadeService interface.
type MockChannelFacadeService struct {
	ctrl     *gomock.Controller
	recorder *MockChannelFacadeServiceMockRecorder
	isgomock struct{}
}

// MockChannelFacadeServiceMockRecorder is the mock recorder for MockChannelFacadeService.
type MockChannelFacadeServiceMockRecorder struct {
	mock *MockChannelFacadeService
}

// NewMockChannelFacadeService creates a new mock instance.
func NewMockChannelFacadeService(ctrl *gomock.Controller) *MockChannelFacadeService {
	mock := &MockChannelFacadeService{ctrl: ctrl}
	mock.recorder = &MockChannelFacadeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelFacadeService) EXPECT() *MockChannelFacadeServiceMockRecorder {
	return m.recorder
}

// DisplayLog mocks base method.
func (m *MockChannelFacadeService) DisplayLog(entry channel.LogEntry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplayLog", entry)
}

// DisplayLog indicates an expected call of DisplayLog.
func (mr *MockChannelFacadeServiceMockRecorder) DisplayLog(entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayLog", reflect.TypeOf((*MockChannelFacadeService)(nil).DisplayLog), entry)
}

// DisplayMessage mocks base method.
func (m *MockChannelFacadeService) DisplayMessage(msg channel.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplayMessage", msg)
}

// DisplayMessage indicates an expected call of DisplayMessage.
func (mr *MockChannelFacadeServiceMockRecorder) DisplayMessage(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayMessage", reflect.TypeOf((*MockChannelFacadeService)(nil).DisplayMessage), msg)
}

// GetLogs mocks base method.
func (m *MockChannelFacadeService) GetLogs(since time.Time, limit int) []channel.LogEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogs", since, limit)
	ret0, _ := ret[0].([]channel.LogEntry)
	return ret0
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockChannelFacadeServiceMockRecorder) GetLogs(since, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockChannelFacadeService)(nil).GetLogs), since, limit)
}

// NotifyAgentLifecycle mocks base method.
func (m *MockChannelFacadeService) NotifyAgentLifecycle(agentID uuid.UUID, role string, added bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyAgentLifecycle", agentID, role, added)
}

// NotifyAgentLifecycle indicates an expected call of NotifyAgentLifecycle.
func (mr *MockChannelFacadeServiceMockRecorder) NotifyAgentLifecycle(agentID, role, added any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyAgentLifecycle", reflect.TypeOf((*MockChannelFacadeService)(nil).NotifyAgentLifecycle), agentID, role, added)
}

// RegisterChannel mocks base method.
func (m *MockChannelFacadeService) RegisterChannel(arg0 channel.Channel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterChannel", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterChannel indicates an expected call of RegisterChannel.
func (mr *MockChannelFacadeServiceMockRecorder) RegisterChannel(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterChannel", reflect.TypeOf((*MockChannelFacadeService)(nil).RegisterChannel), arg0)
}

// SubmitInput mocks base method.
func (m *MockChannelFacadeService) SubmitInput(ctx context.Context, input string) (channel.InputResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitInput", ctx, input)
	ret0, _ := ret[0].(channel.InputResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitInput indicates an expected call of SubmitInput.
func (mr *MockChannelFacadeServiceMockRecorder) SubmitInput(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitInput", reflect.TypeOf((*MockChannelFacadeService)(nil).SubmitInput), ctx, input)
}

// UnregisterChannel mocks base method.
func (m *MockChannelFacadeService) UnregisterChannel(channelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterChannel", channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterChannel indicates an expected call of UnregisterChannel.
func (mr *MockChannelFacadeServiceMockRecorder) UnregisterChannel(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterChannel", reflect.TypeOf((*MockChannelFacadeService)(nil).UnregisterChannel), channelID)
}
