// Code generated by MockGen. DO NOT EDIT.
// Source: tools/bash.go
//
// Generated by this command:
//
//	mockgen -source=tools/bash.go -destination=tools/bash_mock.go -package=tools github.com/denkhaus/gollum/pkg/tools BashToolProvider
//

// Package tools is a generated GoMock package.
package tools

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	gollem "github.com/m-mizutani/gollem"
	gomock "go.uber.org/mock/gomock"
)

// MockBashToolProvider is a mock of BashToolProvider interface.
type MockBashToolProvider struct {
	ctrl     *gomock.Controller
	recorder *MockBashToolProviderMockRecorder
	isgomock struct{}
}

// MockBashToolProviderMockRecorder is the mock recorder for MockBashToolProvider.
type MockBashToolProviderMockRecorder struct {
	mock *MockBashToolProvider
}

// NewMockBashToolProvider creates a new mock instance.
func NewMockBashToolProvider(ctrl *gomock.Controller) *MockBashToolProvider {
	mock := &MockBashToolProvider{ctrl: ctrl}
	mock.recorder = &MockBashToolProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBashToolProvider) EXPECT() *MockBashToolProviderMockRecorder {
	return m.recorder
}

// CreateTool mocks base method.
func (m *MockBashToolProvider) CreateTool(agentID uuid.UUID) gollem.Tool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTool", agentID)
	ret0, _ := ret[0].(gollem.Tool)
	return ret0
}

// CreateTool indicates an expected call of CreateTool.
func (mr *MockBashToolProviderMockRecorder) CreateTool(agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTool", reflect.TypeOf((*MockBashToolProvider)(nil).CreateTool), agentID)
}
