// Code generated by MockGen. DO NOT EDIT.
// Source: tools/flow_tools.go
//
// Generated by this command:
//
//	mockgen -source=tools/flow_tools.go -destination=tools/flow_tools_mock.go -package=tools github.com/denkhaus/gollum/pkg/tools FlowToolsProvider
//

// Package tools is a generated GoMock package.
package tools

import (
	reflect "reflect"

	flows "github.com/denkhaus/gollum/pkg/flows"
	shared "github.com/denkhaus/gollum/pkg/shared"
	uuid "github.com/google/uuid"
	gollem "github.com/m-mizutani/gollem"
	gomock "go.uber.org/mock/gomock"
)

// MockFlowToolsProvider is a mock of FlowToolsProvider interface.
type MockFlowToolsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockFlowToolsProviderMockRecorder
	isgomock struct{}
}

// MockFlowToolsProviderMockRecorder is the mock recorder for MockFlowToolsProvider.
type MockFlowToolsProviderMockRecorder struct {
	mock *MockFlowToolsProvider
}

// NewMockFlowToolsProvider creates a new mock instance.
func NewMockFlowToolsProvider(ctrl *gomock.Controller) *MockFlowToolsProvider {
	mock := &MockFlowToolsProvider{ctrl: ctrl}
	mock.recorder = &MockFlowToolsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowToolsProvider) EXPECT() *MockFlowToolsProviderMockRecorder {
	return m.recorder
}

// CreateTool mocks base method.
func (m *MockFlowToolsProvider) CreateTool(agentID uuid.UUID, flowCtx flows.FlowContext, toolName shared.ToolName) (gollem.Tool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTool", agentID, flowCtx, toolName)
	ret0, _ := ret[0].(gollem.Tool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTool indicates an expected call of CreateTool.
func (mr *MockFlowToolsProviderMockRecorder) CreateTool(agentID, flowCtx, toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTool", reflect.TypeOf((*MockFlowToolsProvider)(nil).CreateTool), agentID, flowCtx, toolName)
}
