// Code generated by MockGen. DO NOT EDIT.
// Source: mcp/registry/registry.go
//
// Generated by this command:
//
//	mockgen -source=mcp/registry/registry.go -destination=mcp/registry/registry_mock.go -package=registry github.com/denkhaus/gollum/pkg/mcp/registry MCPRegistry
//

// Package registry is a generated GoMock package.
package registry

import (
	reflect "reflect"

	gollem "github.com/m-mizutani/gollem"
	gomock "go.uber.org/mock/gomock"
)

// MockMCPRegistry is a mock of MCPRegistry interface.
type MockMCPRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockMCPRegistryMockRecorder
	isgomock struct{}
}

// MockMCPRegistryMockRecorder is the mock recorder for MockMCPRegistry.
type MockMCPRegistryMockRecorder struct {
	mock *MockMCPRegistry
}

// NewMockMCPRegistry creates a new mock instance.
func NewMockMCPRegistry(ctrl *gomock.Controller) *MockMCPRegistry {
	mock := &MockMCPRegistry{ctrl: ctrl}
	mock.recorder = &MockMCPRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMCPRegistry) EXPECT() *MockMCPRegistryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMCPRegistry) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMCPRegistryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMCPRegistry)(nil).Close))
}

// GetToolNames mocks base method.
func (m *MockMCPRegistry) GetToolNames() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToolNames")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetToolNames indicates an expected call of GetToolNames.
func (mr *MockMCPRegistryMockRecorder) GetToolNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToolNames", reflect.TypeOf((*MockMCPRegistry)(nil).GetToolNames))
}

// GetToolSets mocks base method.
func (m *MockMCPRegistry) GetToolSets() []gollem.ToolSet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToolSets")
	ret0, _ := ret[0].([]gollem.ToolSet)
	return ret0
}

// GetToolSets indicates an expected call of GetToolSets.
func (mr *MockMCPRegistryMockRecorder) GetToolSets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToolSets", reflect.TypeOf((*MockMCPRegistry)(nil).GetToolSets))
}
