// Code generated by MockGen. DO NOT EDIT.
// Source: extensions/service.go
//
// Generated by this command:
//
//	mockgen -source=extensions/service.go -destination=extensions/service_mock.go -package=extensions github.com/denkhaus/gollum/pkg/extensions ExtensionService
//

// Package extensions is a generated GoMock package.
package extensions

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExtensionService is a mock of ExtensionService interface.
type MockExtensionService struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionServiceMockRecorder
	isgomock struct{}
}

// MockExtensionServiceMockRecorder is the mock recorder for MockExtensionService.
type MockExtensionServiceMockRecorder struct {
	mock *MockExtensionService
}

// NewMockExtensionService creates a new mock instance.
func NewMockExtensionService(ctrl *gomock.Controller) *MockExtensionService {
	mock := &MockExtensionService{ctrl: ctrl}
	mock.recorder = &MockExtensionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionService) EXPECT() *MockExtensionServiceMockRecorder {
	return m.recorder
}

// GetExtension mocks base method.
func (m *MockExtensionService) GetExtension(name string) (*Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExtension", name)
	ret0, _ := ret[0].(*Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExtension indicates an expected call of GetExtension.
func (mr *MockExtensionServiceMockRecorder) GetExtension(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExtension", reflect.TypeOf((*MockExtensionService)(nil).GetExtension), name)
}

// GetFuncRunner mocks base method.
func (m *MockExtensionService) GetFuncRunner() YaegiFuncRunner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFuncRunner")
	ret0, _ := ret[0].(YaegiFuncRunner)
	return ret0
}

// GetFuncRunner indicates an expected call of GetFuncRunner.
func (mr *MockExtensionServiceMockRecorder) GetFuncRunner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFuncRunner", reflect.TypeOf((*MockExtensionService)(nil).GetFuncRunner))
}

// ListExtensions mocks base method.
func (m *MockExtensionService) ListExtensions() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExtensions")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListExtensions indicates an expected call of ListExtensions.
func (mr *MockExtensionServiceMockRecorder) ListExtensions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExtensions", reflect.TypeOf((*MockExtensionService)(nil).ListExtensions))
}

// LoadAll mocks base method.
func (m *MockExtensionService) LoadAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadAll indicates an expected call of LoadAll.
func (mr *MockExtensionServiceMockRecorder) LoadAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAll", reflect.TypeOf((*MockExtensionService)(nil).LoadAll), ctx)
}
