// Code generated by MockGen. DO NOT EDIT.
// Source: extensions/yaegi_func_runner.go
//
// Generated by this command:
//
//	mockgen -source=extensions/yaegi_func_runner.go -destination=extensions/yaegi_func_runner_mock.go -package=extensions github.com/denkhaus/gollum/pkg/extensions YaegiFuncRunner
//

// Package extensions is a generated GoMock package.
package extensions

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockYaegiFuncRunner is a mock of YaegiFuncRunner interface.
type MockYaegiFuncRunner struct {
	ctrl     *gomock.Controller
	recorder *MockYaegiFuncRunnerMockRecorder
	isgomock struct{}
}

// MockYaegiFuncRunnerMockRecorder is the mock recorder for MockYaegiFuncRunner.
type MockYaegiFuncRunnerMockRecorder struct {
	mock *MockYaegiFuncRunner
}

// NewMockYaegiFuncRunner creates a new mock instance.
func NewMockYaegiFuncRunner(ctrl *gomock.Controller) *MockYaegiFuncRunner {
	mock := &MockYaegiFuncRunner{ctrl: ctrl}
	mock.recorder = &MockYaegiFuncRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockYaegiFuncRunner) EXPECT() *MockYaegiFuncRunnerMockRecorder {
	return m.recorder
}

// ExecuteFunc mocks base method.
func (m *MockYaegiFuncRunner) ExecuteFunc(name string, args map[string]any) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteFunc", name, args)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteFunc indicates an expected call of ExecuteFunc.
func (mr *MockYaegiFuncRunnerMockRecorder) ExecuteFunc(name, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteFunc", reflect.TypeOf((*MockYaegiFuncRunner)(nil).ExecuteFunc), name, args)
}

// ListFuncs mocks base method.
func (m *MockYaegiFuncRunner) ListFuncs() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFuncs")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListFuncs indicates an expected call of ListFuncs.
func (mr *MockYaegiFuncRunnerMockRecorder) ListFuncs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFuncs", reflect.TypeOf((*MockYaegiFuncRunner)(nil).ListFuncs))
}

// LoadFunc mocks base method.
func (m *MockYaegiFuncRunner) LoadFunc(name, source string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFunc", name, source)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadFunc indicates an expected call of LoadFunc.
func (mr *MockYaegiFuncRunnerMockRecorder) LoadFunc(name, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFunc", reflect.TypeOf((*MockYaegiFuncRunner)(nil).LoadFunc), name, source)
}
