// Code generated by MockGen. DO NOT EDIT.
// Source: extensions/yaegi.go
//
// Generated by this command:
//
//	mockgen -source=extensions/yaegi.go -destination=extensions/yaegi_mock.go -package=extensions github.com/denkhaus/gollum/pkg/extensions YaegiLoader
//

// Package extensions is a generated GoMock package.
package extensions

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockYaegiLoader is a mock of YaegiLoader interface.
type MockYaegiLoader struct {
	ctrl     *gomock.Controller
	recorder *MockYaegiLoaderMockRecorder
	isgomock struct{}
}

// MockYaegiLoaderMockRecorder is the mock recorder for MockYaegiLoader.
type MockYaegiLoaderMockRecorder struct {
	mock *MockYaegiLoader
}

// NewMockYaegiLoader creates a new mock instance.
func NewMockYaegiLoader(ctrl *gomock.Controller) *MockYaegiLoader {
	mock := &MockYaegiLoader{ctrl: ctrl}
	mock.recorder = &MockYaegiLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockYaegiLoader) EXPECT() *MockYaegiLoaderMockRecorder {
	return m.recorder
}

// GetExtension mocks base method.
func (m *MockYaegiLoader) GetExtension(name string) (*Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExtension", name)
	ret0, _ := ret[0].(*Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExtension indicates an expected call of GetExtension.
func (mr *MockYaegiLoaderMockRecorder) GetExtension(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExtension", reflect.TypeOf((*MockYaegiLoader)(nil).GetExtension), name)
}

// InitExtension mocks base method.
func (m *MockYaegiLoader) InitExtension(ext *Extension) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitExtension", ext)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitExtension indicates an expected call of InitExtension.
func (mr *MockYaegiLoaderMockRecorder) InitExtension(ext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitExtension", reflect.TypeOf((*MockYaegiLoader)(nil).InitExtension), ext)
}

// ListExtensions mocks base method.
func (m *MockYaegiLoader) ListExtensions() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExtensions")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListExtensions indicates an expected call of ListExtensions.
func (mr *MockYaegiLoaderMockRecorder) ListExtensions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExtensions", reflect.TypeOf((*MockYaegiLoader)(nil).ListExtensions))
}

// LoadExtension mocks base method.
func (m *MockYaegiLoader) LoadExtension(path string) (*Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadExtension", path)
	ret0, _ := ret[0].(*Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadExtension indicates an expected call of LoadExtension.
func (mr *MockYaegiLoaderMockRecorder) LoadExtension(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadExtension", reflect.TypeOf((*MockYaegiLoader)(nil).LoadExtension), path)
}

// UnloadExtension mocks base method.
func (m *MockYaegiLoader) UnloadExtension(ext *Extension) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnloadExtension", ext)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnloadExtension indicates an expected call of UnloadExtension.
func (mr *MockYaegiLoaderMockRecorder) UnloadExtension(ext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnloadExtension", reflect.TypeOf((*MockYaegiLoader)(nil).UnloadExtension), ext)
}
