// Code generated by MockGen. DO NOT EDIT.
// Source: session/manager.go
//
// Generated by this command:
//
//	mockgen -source=session/manager.go -destination=session/manager_mock.go -package=session github.com/denkhaus/gollum/pkg/session SessionManager
//

// Package session is a generated GoMock package.
package session

import (
	context "context"
	reflect "reflect"

	shared "github.com/denkhaus/gollum/pkg/shared"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionManager is a mock of SessionManager interface.
type MockSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerMockRecorder
	isgomock struct{}
}

// MockSessionManagerMockRecorder is the mock recorder for MockSessionManager.
type MockSessionManagerMockRecorder struct {
	mock *MockSessionManager
}

// NewMockSessionManager creates a new mock instance.
func NewMockSessionManager(ctrl *gomock.Controller) *MockSessionManager {
	mock := &MockSessionManager{ctrl: ctrl}
	mock.recorder = &MockSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManager) EXPECT() *MockSessionManagerMockRecorder {
	return m.recorder
}

// CloseSession mocks base method.
func (m *MockSessionManager) CloseSession(sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSession", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSession indicates an expected call of CloseSession.
func (mr *MockSessionManagerMockRecorder) CloseSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSession", reflect.TypeOf((*MockSessionManager)(nil).CloseSession), sessionID)
}

// CreateSession mocks base method.
func (m *MockSessionManager) CreateSession(ctx context.Context, sessionCtx *shared.SessionContext) (*shared.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, sessionCtx)
	ret0, _ := ret[0].(*shared.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionManagerMockRecorder) CreateSession(ctx, sessionCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionManager)(nil).CreateSession), ctx, sessionCtx)
}

// ForkSession mocks base method.
func (m *MockSessionManager) ForkSession(ctx context.Context, sessionID uuid.UUID) (*shared.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForkSession", ctx, sessionID)
	ret0, _ := ret[0].(*shared.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForkSession indicates an expected call of ForkSession.
func (mr *MockSessionManagerMockRecorder) ForkSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForkSession", reflect.TypeOf((*MockSessionManager)(nil).ForkSession), ctx, sessionID)
}

// GetOrCreateSession mocks base method.
func (m *MockSessionManager) GetOrCreateSession(ctx context.Context, sessionCtx *shared.SessionContext) (*shared.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateSession", ctx, sessionCtx)
	ret0, _ := ret[0].(*shared.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateSession indicates an expected call of GetOrCreateSession.
func (mr *MockSessionManagerMockRecorder) GetOrCreateSession(ctx, sessionCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateSession", reflect.TypeOf((*MockSessionManager)(nil).GetOrCreateSession), ctx, sessionCtx)
}

// GetSession mocks base method.
func (m *MockSessionManager) GetSession(sessionID uuid.UUID) (*shared.Session, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", sessionID)
	ret0, _ := ret[0].(*shared.Session)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionManagerMockRecorder) GetSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionManager)(nil).GetSession), sessionID)
}

// GetSessionsByChannel mocks base method.
func (m *MockSessionManager) GetSessionsByChannel(channelID uuid.UUID) []*shared.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionsByChannel", channelID)
	ret0, _ := ret[0].([]*shared.Session)
	return ret0
}

// GetSessionsByChannel indicates an expected call of GetSessionsByChannel.
func (mr *MockSessionManagerMockRecorder) GetSessionsByChannel(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionsByChannel", reflect.TypeOf((*MockSessionManager)(nil).GetSessionsByChannel), channelID)
}

// ListSessions mocks base method.
func (m *MockSessionManager) ListSessions(ctx context.Context) ([]*shared.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions", ctx)
	ret0, _ := ret[0].([]*shared.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockSessionManagerMockRecorder) ListSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockSessionManager)(nil).ListSessions), ctx)
}

// LoadSession mocks base method.
func (m *MockSessionManager) LoadSession(ctx context.Context, sessionID uuid.UUID) (*shared.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSession", ctx, sessionID)
	ret0, _ := ret[0].(*shared.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSession indicates an expected call of LoadSession.
func (mr *MockSessionManagerMockRecorder) LoadSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSession", reflect.TypeOf((*MockSessionManager)(nil).LoadSession), ctx, sessionID)
}

// ResumeSession mocks base method.
func (m *MockSessionManager) ResumeSession(ctx context.Context, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeSession indicates an expected call of ResumeSession.
func (mr *MockSessionManagerMockRecorder) ResumeSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeSession", reflect.TypeOf((*MockSessionManager)(nil).ResumeSession), ctx, sessionID)
}
