// Code generated by MockGen. DO NOT EDIT.
// Source: session/manager.go
//
// Generated by this command:
//
//	mockgen -source=session/manager.go -destination=session/manager_mock.go -package=session github.com/denkhaus/gollum/pkg/session SessionManager
//

// Package session is a generated GoMock package.
package session
