// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/shared/acp.go
//
// Generated by this command:
//
//	mockgen -source=pkg/shared/acp.go -destination=pkg/acp/service_mock.go -package=acp github.com/denkhaus/gollum/pkg/shared ACPService
//

// Package acp is a generated GoMock package.
package acp

import (
	context "context"
	http "net/http"
	reflect "reflect"

	shared "github.com/denkhaus/gollum/pkg/shared"
	acp "github.com/ironpark/go-acp"
	gomock "go.uber.org/mock/gomock"
)

// MockACPService is a mock of ACPService interface.
type MockACPService struct {
	ctrl     *gomock.Controller
	recorder *MockACPServiceMockRecorder
	isgomock struct{}
}

// MockACPServiceMockRecorder is the mock recorder for MockACPService.
type MockACPServiceMockRecorder struct {
	mock *MockACPService
}

// NewMockACPService creates a new mock instance.
func NewMockACPService(ctrl *gomock.Controller) *MockACPService {
	mock := &MockACPService{ctrl: ctrl}
	mock.recorder = &MockACPServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockACPService) EXPECT() *MockACPServiceMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockACPService) Authenticate(ctx context.Context, params *acp.AuthenticateRequest) (*acp.AuthenticateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, params)
	ret0, _ := ret[0].(*acp.AuthenticateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockACPServiceMockRecorder) Authenticate(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockACPService)(nil).Authenticate), ctx, params)
}

// Cancel mocks base method.
func (m *MockACPService) Cancel(ctx context.Context, params *acp.CancelNotification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockACPServiceMockRecorder) Cancel(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockACPService)(nil).Cancel), ctx, params)
}

// GetHandler mocks base method.
func (m *MockACPService) GetHandler() http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHandler")
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// GetHandler indicates an expected call of GetHandler.
func (mr *MockACPServiceMockRecorder) GetHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHandler", reflect.TypeOf((*MockACPService)(nil).GetHandler))
}

// Initialize mocks base method.
func (m *MockACPService) Initialize(ctx context.Context, params *acp.InitializeRequest) (*acp.InitializeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", ctx, params)
	ret0, _ := ret[0].(*acp.InitializeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Initialize indicates an expected call of Initialize.
func (mr *MockACPServiceMockRecorder) Initialize(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockACPService)(nil).Initialize), ctx, params)
}

// Prompt mocks base method.
func (m *MockACPService) Prompt(ctx context.Context, params *acp.PromptRequest) (*acp.PromptResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prompt", ctx, params)
	ret0, _ := ret[0].(*acp.PromptResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prompt indicates an expected call of Prompt.
func (mr *MockACPServiceMockRecorder) Prompt(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prompt", reflect.TypeOf((*MockACPService)(nil).Prompt), ctx, params)
}

// SetClient mocks base method.
func (m *MockACPService) SetClient(client acp.Client) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetClient", client)
}

// SetClient indicates an expected call of SetClient.
func (mr *MockACPServiceMockRecorder) SetClient(client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetClient", reflect.TypeOf((*MockACPService)(nil).SetClient), client)
}

// SetSessionConfigOption mocks base method.
func (m *MockACPService) SetSessionConfigOption(ctx context.Context, params *acp.SetSessionConfigOptionRequest) (*acp.SetSessionConfigOptionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionConfigOption", ctx, params)
	ret0, _ := ret[0].(*acp.SetSessionConfigOptionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetSessionConfigOption indicates an expected call of SetSessionConfigOption.
func (mr *MockACPServiceMockRecorder) SetSessionConfigOption(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionConfigOption", reflect.TypeOf((*MockACPService)(nil).SetSessionConfigOption), ctx, params)
}

// SetSessionMode mocks base method.
func (m *MockACPService) SetSessionMode(ctx context.Context, params *acp.SetSessionModeRequest) (*acp.SetSessionModeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionMode", ctx, params)
	ret0, _ := ret[0].(*acp.SetSessionModeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetSessionMode indicates an expected call of SetSessionMode.
func (mr *MockACPServiceMockRecorder) SetSessionMode(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionMode", reflect.TypeOf((*MockACPService)(nil).SetSessionMode), ctx, params)
}

// SetSessionStore mocks base method.
func (m *MockACPService) SetSessionStore(store acp.SessionStore[*shared.ACPSession]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSessionStore", store)
}

// SetSessionStore indicates an expected call of SetSessionStore.
func (mr *MockACPServiceMockRecorder) SetSessionStore(store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionStore", reflect.TypeOf((*MockACPService)(nil).SetSessionStore), store)
}
