// Code generated by MockGen. DO NOT EDIT.
// Source: acp/service.go
//
// Generated by this command:
//
//	mockgen -source=acp/service.go -destination=acp/service_mock.go -package=acp github.com/denkhaus/gollum/pkg/acp Service
//

// Package acp is a generated GoMock package.
package acp

import (
	context "context"
	reflect "reflect"

	acp "github.com/ironpark/go-acp"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockService) Authenticate(ctx context.Context, params *acp.AuthenticateRequest) (*acp.AuthenticateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, params)
	ret0, _ := ret[0].(*acp.AuthenticateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockServiceMockRecorder) Authenticate(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockService)(nil).Authenticate), ctx, params)
}

// Cancel mocks base method.
func (m *MockService) Cancel(ctx context.Context, params *acp.CancelNotification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockServiceMockRecorder) Cancel(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockService)(nil).Cancel), ctx, params)
}

// Initialize mocks base method.
func (m *MockService) Initialize(ctx context.Context, params *acp.InitializeRequest) (*acp.InitializeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", ctx, params)
	ret0, _ := ret[0].(*acp.InitializeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Initialize indicates an expected call of Initialize.
func (mr *MockServiceMockRecorder) Initialize(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockService)(nil).Initialize), ctx, params)
}

// Prompt mocks base method.
func (m *MockService) Prompt(ctx context.Context, params *acp.PromptRequest) (*acp.PromptResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prompt", ctx, params)
	ret0, _ := ret[0].(*acp.PromptResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prompt indicates an expected call of Prompt.
func (mr *MockServiceMockRecorder) Prompt(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prompt", reflect.TypeOf((*MockService)(nil).Prompt), ctx, params)
}

// SetClient mocks base method.
func (m *MockService) SetClient(client acp.Client) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetClient", client)
}

// SetClient indicates an expected call of SetClient.
func (mr *MockServiceMockRecorder) SetClient(client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetClient", reflect.TypeOf((*MockService)(nil).SetClient), client)
}

// SetSessionConfigOption mocks base method.
func (m *MockService) SetSessionConfigOption(ctx context.Context, params *acp.SetSessionConfigOptionRequest) (*acp.SetSessionConfigOptionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionConfigOption", ctx, params)
	ret0, _ := ret[0].(*acp.SetSessionConfigOptionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetSessionConfigOption indicates an expected call of SetSessionConfigOption.
func (mr *MockServiceMockRecorder) SetSessionConfigOption(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionConfigOption", reflect.TypeOf((*MockService)(nil).SetSessionConfigOption), ctx, params)
}

// SetSessionMode mocks base method.
func (m *MockService) SetSessionMode(ctx context.Context, params *acp.SetSessionModeRequest) (*acp.SetSessionModeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionMode", ctx, params)
	ret0, _ := ret[0].(*acp.SetSessionModeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetSessionMode indicates an expected call of SetSessionMode.
func (mr *MockServiceMockRecorder) SetSessionMode(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionMode", reflect.TypeOf((*MockService)(nil).SetSessionMode), ctx, params)
}

// SetSessionStore mocks base method.
func (m *MockService) SetSessionStore(store acp.SessionStore[*AcpSession]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSessionStore", store)
}

// SetSessionStore indicates an expected call of SetSessionStore.
func (mr *MockServiceMockRecorder) SetSessionStore(store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionStore", reflect.TypeOf((*MockService)(nil).SetSessionStore), store)
}
