// Code generated by MockGen. DO NOT EDIT.
// Source: channel/interface.go
//
// Generated by this command:
//
//	mockgen -source=channel/interface.go -destination=channel/facade_mock.go -package=channel github.com/denkhaus/gollum/pkg/channel ChannelFacade,Channel
//

// Package channel is a generated GoMock package.
package channel

import (
	context "context"
	reflect "reflect"

	shared "github.com/denkhaus/gollum/pkg/shared"
	uuid "github.com/google/uuid"
	do "github.com/samber/do/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockChannel is a mock of Channel interface.
type MockChannel struct {
	ctrl     *gomock.Controller
	recorder *MockChannelMockRecorder
	isgomock struct{}
}

// MockChannelMockRecorder is the mock recorder for MockChannel.
type MockChannelMockRecorder struct {
	mock *MockChannel
}

// NewMockChannel creates a new mock instance.
func NewMockChannel(ctrl *gomock.Controller) *MockChannel {
	mock := &MockChannel{ctrl: ctrl}
	mock.recorder = &MockChannelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannel) EXPECT() *MockChannelMockRecorder {
	return m.recorder
}

// ID mocks base method.
func (m *MockChannel) ID() uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockChannelMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockChannel)(nil).ID))
}

// OnAgentLifecycle mocks base method.
func (m *MockChannel) OnAgentLifecycle(event AgentLifecycleEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnAgentLifecycle", event)
}

// OnAgentLifecycle indicates an expected call of OnAgentLifecycle.
func (mr *MockChannelMockRecorder) OnAgentLifecycle(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnAgentLifecycle", reflect.TypeOf((*MockChannel)(nil).OnAgentLifecycle), event)
}

// OnLog mocks base method.
func (m *MockChannel) OnLog(entry shared.LogEntry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnLog", entry)
}

// OnLog indicates an expected call of OnLog.
func (mr *MockChannelMockRecorder) OnLog(entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnLog", reflect.TypeOf((*MockChannel)(nil).OnLog), entry)
}

// OnMessage mocks base method.
func (m *MockChannel) OnMessage(msg Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnMessage", msg)
}

// OnMessage indicates an expected call of OnMessage.
func (mr *MockChannelMockRecorder) OnMessage(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnMessage", reflect.TypeOf((*MockChannel)(nil).OnMessage), msg)
}

// Start mocks base method.
func (m *MockChannel) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockChannelMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockChannel)(nil).Start), ctx)
}

// MockChannelFacade is a mock of ChannelFacade interface.
type MockChannelFacade struct {
	ctrl     *gomock.Controller
	recorder *MockChannelFacadeMockRecorder
	isgomock struct{}
}

// MockChannelFacadeMockRecorder is the mock recorder for MockChannelFacade.
type MockChannelFacadeMockRecorder struct {
	mock *MockChannelFacade
}

// NewMockChannelFacade creates a new mock instance.
func NewMockChannelFacade(ctrl *gomock.Controller) *MockChannelFacade {
	mock := &MockChannelFacade{ctrl: ctrl}
	mock.recorder = &MockChannelFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelFacade) EXPECT() *MockChannelFacadeMockRecorder {
	return m.recorder
}

// CancelInput mocks base method.
func (m *MockChannelFacade) CancelInput(sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelInput", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelInput indicates an expected call of CancelInput.
func (mr *MockChannelFacadeMockRecorder) CancelInput(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelInput", reflect.TypeOf((*MockChannelFacade)(nil).CancelInput), sessionID)
}

// CreateChannel mocks base method.
func (m *MockChannelFacade) CreateChannel(identifier ChannelIdentifier, opts ...ChannelOption) (Channel, error) {
	m.ctrl.T.Helper()
	varargs := []any{identifier}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateChannel", varargs...)
	ret0, _ := ret[0].(Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChannel indicates an expected call of CreateChannel.
func (mr *MockChannelFacadeMockRecorder) CreateChannel(identifier any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{identifier}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChannel", reflect.TypeOf((*MockChannelFacade)(nil).CreateChannel), varargs...)
}

// DiscoverProviders mocks base method.
func (m *MockChannelFacade) DiscoverProviders(injector do.Injector) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscoverProviders", injector)
	ret0, _ := ret[0].(error)
	return ret0
}

// DiscoverProviders indicates an expected call of DiscoverProviders.
func (mr *MockChannelFacadeMockRecorder) DiscoverProviders(injector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscoverProviders", reflect.TypeOf((*MockChannelFacade)(nil).DiscoverProviders), injector)
}

// DisplayMessage mocks base method.
func (m *MockChannelFacade) DisplayMessage(msg Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplayMessage", msg)
}

// DisplayMessage indicates an expected call of DisplayMessage.
func (mr *MockChannelFacadeMockRecorder) DisplayMessage(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayMessage", reflect.TypeOf((*MockChannelFacade)(nil).DisplayMessage), msg)
}

// ForwardLog mocks base method.
func (m *MockChannelFacade) ForwardLog(entry shared.LogEntry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ForwardLog", entry)
}

// ForwardLog indicates an expected call of ForwardLog.
func (mr *MockChannelFacadeMockRecorder) ForwardLog(entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForwardLog", reflect.TypeOf((*MockChannelFacade)(nil).ForwardLog), entry)
}

// NotifyAgentLifecycle mocks base method.
func (m *MockChannelFacade) NotifyAgentLifecycle(agentID, channelID uuid.UUID, sessionID, role string, added bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyAgentLifecycle", agentID, channelID, sessionID, role, added)
}

// NotifyAgentLifecycle indicates an expected call of NotifyAgentLifecycle.
func (mr *MockChannelFacadeMockRecorder) NotifyAgentLifecycle(agentID, channelID, sessionID, role, added any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyAgentLifecycle", reflect.TypeOf((*MockChannelFacade)(nil).NotifyAgentLifecycle), agentID, channelID, sessionID, role, added)
}

// RegisterChannel mocks base method.
func (m *MockChannelFacade) RegisterChannel(channel Channel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterChannel", channel)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterChannel indicates an expected call of RegisterChannel.
func (mr *MockChannelFacadeMockRecorder) RegisterChannel(channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterChannel", reflect.TypeOf((*MockChannelFacade)(nil).RegisterChannel), channel)
}

// SubmitInput mocks base method.
func (m *MockChannelFacade) SubmitInput(ctx context.Context, channelID uuid.UUID, sessionID, input string) (*InputResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitInput", ctx, channelID, sessionID, input)
	ret0, _ := ret[0].(*InputResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitInput indicates an expected call of SubmitInput.
func (mr *MockChannelFacadeMockRecorder) SubmitInput(ctx, channelID, sessionID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitInput", reflect.TypeOf((*MockChannelFacade)(nil).SubmitInput), ctx, channelID, sessionID, input)
}

// UnregisterChannel mocks base method.
func (m *MockChannelFacade) UnregisterChannel(channelID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterChannel", channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterChannel indicates an expected call of UnregisterChannel.
func (mr *MockChannelFacadeMockRecorder) UnregisterChannel(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterChannel", reflect.TypeOf((*MockChannelFacade)(nil).UnregisterChannel), channelID)
}
