// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/channel/handler.go
//
// Generated by this command:
//
//	mockgen -source=pkg/channel/handler.go -destination=pkg/channel/handler_mock.go -package=channel github.com/denkhaus/gollum/pkg/channel InputHandler
//

// Package channel is a generated GoMock package.
package channel

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockInputHandler is a mock of InputHandler interface.
type MockInputHandler struct {
	ctrl     *gomock.Controller
	recorder *MockInputHandlerMockRecorder
	isgomock struct{}
}

// MockInputHandlerMockRecorder is the mock recorder for MockInputHandler.
type MockInputHandlerMockRecorder struct {
	mock *MockInputHandler
}

// NewMockInputHandler creates a new mock instance.
func NewMockInputHandler(ctrl *gomock.Controller) *MockInputHandler {
	mock := &MockInputHandler{ctrl: ctrl}
	mock.recorder = &MockInputHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInputHandler) EXPECT() *MockInputHandlerMockRecorder {
	return m.recorder
}

// CancelInput mocks base method.
func (m *MockInputHandler) CancelInput(sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelInput", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelInput indicates an expected call of CancelInput.
func (mr *MockInputHandlerMockRecorder) CancelInput(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelInput", reflect.TypeOf((*MockInputHandler)(nil).CancelInput), sessionID)
}

// HandleInput mocks base method.
func (m *MockInputHandler) HandleInput(ctx context.Context, channelID uuid.UUID, sessionID, input string) (*InputResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleInput", ctx, channelID, sessionID, input)
	ret0, _ := ret[0].(*InputResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleInput indicates an expected call of HandleInput.
func (mr *MockInputHandlerMockRecorder) HandleInput(ctx, channelID, sessionID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleInput", reflect.TypeOf((*MockInputHandler)(nil).HandleInput), ctx, channelID, sessionID, input)
}
