// Code generated by MockGen. DO NOT EDIT.
// Source: logger/logger.go
//
// Generated by this command:
//
//	mockgen -source=logger/logger.go -destination=logger/logger_mock.go -package=logger github.com/denkhaus/gollum/pkg/logger LoggerService
//

// Package logger is a generated GoMock package.
package logger

import (
	reflect "reflect"

	shared "github.com/denkhaus/gollum/pkg/shared"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockLoggerService is a mock of LoggerService interface.
type MockLoggerService struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerServiceMockRecorder
	isgomock struct{}
}

// MockLoggerServiceMockRecorder is the mock recorder for MockLoggerService.
type MockLoggerServiceMockRecorder struct {
	mock *MockLoggerService
}

// NewMockLoggerService creates a new mock instance.
func NewMockLoggerService(ctrl *gomock.Controller) *MockLoggerService {
	mock := &MockLoggerService{ctrl: ctrl}
	mock.recorder = &MockLoggerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoggerService) EXPECT() *MockLoggerServiceMockRecorder {
	return m.recorder
}

// CloseFileLogging mocks base method.
func (m *MockLoggerService) CloseFileLogging() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseFileLogging")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseFileLogging indicates an expected call of CloseFileLogging.
func (mr *MockLoggerServiceMockRecorder) CloseFileLogging() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseFileLogging", reflect.TypeOf((*MockLoggerService)(nil).CloseFileLogging))
}

// Debug mocks base method.
func (m *MockLoggerService) Debug(msg string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerServiceMockRecorder) Debug(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLoggerService)(nil).Debug), varargs...)
}

// DebugWithContext mocks base method.
func (m *MockLoggerService) DebugWithContext(msg string, ctx shared.LoggingContext, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg, ctx}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "DebugWithContext", varargs...)
}

// DebugWithContext indicates an expected call of DebugWithContext.
func (mr *MockLoggerServiceMockRecorder) DebugWithContext(msg, ctx any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg, ctx}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebugWithContext", reflect.TypeOf((*MockLoggerService)(nil).DebugWithContext), varargs...)
}

// DebugWithFlowStep mocks base method.
func (m *MockLoggerService) DebugWithFlowStep(msg, flowName, stateName, stepType string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg, flowName, stateName, stepType}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "DebugWithFlowStep", varargs...)
}

// DebugWithFlowStep indicates an expected call of DebugWithFlowStep.
func (mr *MockLoggerServiceMockRecorder) DebugWithFlowStep(msg, flowName, stateName, stepType any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg, flowName, stateName, stepType}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebugWithFlowStep", reflect.TypeOf((*MockLoggerService)(nil).DebugWithFlowStep), varargs...)
}

// Debugf mocks base method.
func (m *MockLoggerService) Debugf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockLoggerServiceMockRecorder) Debugf(template any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*MockLoggerService)(nil).Debugf), varargs...)
}

// EnableFileLogging mocks base method.
func (m *MockLoggerService) EnableFileLogging(gollumDir string, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableFileLogging", gollumDir, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableFileLogging indicates an expected call of EnableFileLogging.
func (mr *MockLoggerServiceMockRecorder) EnableFileLogging(gollumDir, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableFileLogging", reflect.TypeOf((*MockLoggerService)(nil).EnableFileLogging), gollumDir, sessionID)
}

// Error mocks base method.
func (m *MockLoggerService) Error(msg string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerServiceMockRecorder) Error(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLoggerService)(nil).Error), varargs...)
}

// ErrorWithContext mocks base method.
func (m *MockLoggerService) ErrorWithContext(msg string, ctx shared.LoggingContext, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg, ctx}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ErrorWithContext", varargs...)
}

// ErrorWithContext indicates an expected call of ErrorWithContext.
func (mr *MockLoggerServiceMockRecorder) ErrorWithContext(msg, ctx any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg, ctx}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorWithContext", reflect.TypeOf((*MockLoggerService)(nil).ErrorWithContext), varargs...)
}

// ErrorWithFlowStep mocks base method.
func (m *MockLoggerService) ErrorWithFlowStep(msg, flowName, stateName, stepType string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg, flowName, stateName, stepType}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ErrorWithFlowStep", varargs...)
}

// ErrorWithFlowStep indicates an expected call of ErrorWithFlowStep.
func (mr *MockLoggerServiceMockRecorder) ErrorWithFlowStep(msg, flowName, stateName, stepType any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg, flowName, stateName, stepType}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorWithFlowStep", reflect.TypeOf((*MockLoggerService)(nil).ErrorWithFlowStep), varargs...)
}

// Errorf mocks base method.
func (m *MockLoggerService) Errorf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockLoggerServiceMockRecorder) Errorf(template any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockLoggerService)(nil).Errorf), varargs...)
}

// Flush mocks base method.
func (m *MockLoggerService) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockLoggerServiceMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockLoggerService)(nil).Flush))
}

// GetLogStats mocks base method.
func (m *MockLoggerService) GetLogStats() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogStats")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetLogStats indicates an expected call of GetLogStats.
func (mr *MockLoggerServiceMockRecorder) GetLogStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogStats", reflect.TypeOf((*MockLoggerService)(nil).GetLogStats))
}

// GetLogger mocks base method.
func (m *MockLoggerService) GetLogger() *zap.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogger")
	ret0, _ := ret[0].(*zap.Logger)
	return ret0
}

// GetLogger indicates an expected call of GetLogger.
func (mr *MockLoggerServiceMockRecorder) GetLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogger", reflect.TypeOf((*MockLoggerService)(nil).GetLogger))
}

// GetLogs mocks base method.
func (m *MockLoggerService) GetLogs(filter LogFilter) []LogEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogs", filter)
	ret0, _ := ret[0].([]LogEntry)
	return ret0
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockLoggerServiceMockRecorder) GetLogs(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockLoggerService)(nil).GetLogs), filter)
}

// Info mocks base method.
func (m *MockLoggerService) Info(msg string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerServiceMockRecorder) Info(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLoggerService)(nil).Info), varargs...)
}

// InfoWithContext mocks base method.
func (m *MockLoggerService) InfoWithContext(msg string, ctx shared.LoggingContext, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg, ctx}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InfoWithContext", varargs...)
}

// InfoWithContext indicates an expected call of InfoWithContext.
func (mr *MockLoggerServiceMockRecorder) InfoWithContext(msg, ctx any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg, ctx}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoWithContext", reflect.TypeOf((*MockLoggerService)(nil).InfoWithContext), varargs...)
}

// InfoWithFlowStep mocks base method.
func (m *MockLoggerService) InfoWithFlowStep(msg, flowName, stateName, stepType string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg, flowName, stateName, stepType}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InfoWithFlowStep", varargs...)
}

// InfoWithFlowStep indicates an expected call of InfoWithFlowStep.
func (mr *MockLoggerServiceMockRecorder) InfoWithFlowStep(msg, flowName, stateName, stepType any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg, flowName, stateName, stepType}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoWithFlowStep", reflect.TypeOf((*MockLoggerService)(nil).InfoWithFlowStep), varargs...)
}

// Infof mocks base method.
func (m *MockLoggerService) Infof(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockLoggerServiceMockRecorder) Infof(template any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockLoggerService)(nil).Infof), varargs...)
}

// IsTUIMode mocks base method.
func (m *MockLoggerService) IsTUIMode() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTUIMode")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTUIMode indicates an expected call of IsTUIMode.
func (mr *MockLoggerServiceMockRecorder) IsTUIMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTUIMode", reflect.TypeOf((*MockLoggerService)(nil).IsTUIMode))
}

// SetLogForwarder mocks base method.
func (m *MockLoggerService) SetLogForwarder(forwarder shared.LogForwarder) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogForwarder", forwarder)
}

// SetLogForwarder indicates an expected call of SetLogForwarder.
func (mr *MockLoggerServiceMockRecorder) SetLogForwarder(forwarder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogForwarder", reflect.TypeOf((*MockLoggerService)(nil).SetLogForwarder), forwarder)
}

// SetTUIMode mocks base method.
func (m *MockLoggerService) SetTUIMode(enabled bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTUIMode", enabled)
}

// SetTUIMode indicates an expected call of SetTUIMode.
func (mr *MockLoggerServiceMockRecorder) SetTUIMode(enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTUIMode", reflect.TypeOf((*MockLoggerService)(nil).SetTUIMode), enabled)
}

// Warn mocks base method.
func (m *MockLoggerService) Warn(msg string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerServiceMockRecorder) Warn(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLoggerService)(nil).Warn), varargs...)
}

// WarnWithContext mocks base method.
func (m *MockLoggerService) WarnWithContext(msg string, ctx shared.LoggingContext, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg, ctx}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "WarnWithContext", varargs...)
}

// WarnWithContext indicates an expected call of WarnWithContext.
func (mr *MockLoggerServiceMockRecorder) WarnWithContext(msg, ctx any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg, ctx}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnWithContext", reflect.TypeOf((*MockLoggerService)(nil).WarnWithContext), varargs...)
}

// WarnWithFlowStep mocks base method.
func (m *MockLoggerService) WarnWithFlowStep(msg, flowName, stateName, stepType string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg, flowName, stateName, stepType}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "WarnWithFlowStep", varargs...)
}

// WarnWithFlowStep indicates an expected call of WarnWithFlowStep.
func (mr *MockLoggerServiceMockRecorder) WarnWithFlowStep(msg, flowName, stateName, stepType any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg, flowName, stateName, stepType}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnWithFlowStep", reflect.TypeOf((*MockLoggerService)(nil).WarnWithFlowStep), varargs...)
}

// Warnf mocks base method.
func (m *MockLoggerService) Warnf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf.
func (mr *MockLoggerServiceMockRecorder) Warnf(template any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockLoggerService)(nil).Warnf), varargs...)
}
