// Code generated by MockGen. DO NOT EDIT.
// Source: registry/registry.go
//
// Generated by this command:
//
//	mockgen -source=registry/registry.go -destination=registry/registry_mock.go -package=registry github.com/denkhaus/gollum/pkg/registry AgentRegistry
//

// Package registry is a generated GoMock package.
package registry

import (
	context "context"
	reflect "reflect"
	time "time"

	shared "github.com/denkhaus/gollum/pkg/shared"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentRegistry is a mock of AgentRegistry interface.
type MockAgentRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockAgentRegistryMockRecorder
	isgomock struct{}
}

// MockAgentRegistryMockRecorder is the mock recorder for MockAgentRegistry.
type MockAgentRegistryMockRecorder struct {
	mock *MockAgentRegistry
}

// NewMockAgentRegistry creates a new mock instance.
func NewMockAgentRegistry(ctrl *gomock.Controller) *MockAgentRegistry {
	mock := &MockAgentRegistry{ctrl: ctrl}
	mock.recorder = &MockAgentRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentRegistry) EXPECT() *MockAgentRegistryMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockAgentRegistry) Cleanup(agentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockAgentRegistryMockRecorder) Cleanup(agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockAgentRegistry)(nil).Cleanup), agentID)
}

// DeleteAgentResult mocks base method.
func (m *MockAgentRegistry) DeleteAgentResult(agentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgentResult", agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAgentResult indicates an expected call of DeleteAgentResult.
func (mr *MockAgentRegistryMockRecorder) DeleteAgentResult(agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgentResult", reflect.TypeOf((*MockAgentRegistry)(nil).DeleteAgentResult), agentID)
}

// GetAgent mocks base method.
func (m *MockAgentRegistry) GetAgent(agentID uuid.UUID) (shared.Agent, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgent", agentID)
	ret0, _ := ret[0].(shared.Agent)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetAgent indicates an expected call of GetAgent.
func (mr *MockAgentRegistryMockRecorder) GetAgent(agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgent", reflect.TypeOf((*MockAgentRegistry)(nil).GetAgent), agentID)
}

// GetAgentResult mocks base method.
func (m *MockAgentRegistry) GetAgentResult(agentID uuid.UUID) (*shared.AgentResult, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentResult", agentID)
	ret0, _ := ret[0].(*shared.AgentResult)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetAgentResult indicates an expected call of GetAgentResult.
func (mr *MockAgentRegistryMockRecorder) GetAgentResult(agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentResult", reflect.TypeOf((*MockAgentRegistry)(nil).GetAgentResult), agentID)
}

// GetChildren mocks base method.
func (m *MockAgentRegistry) GetChildren(parentID uuid.UUID) []shared.Agent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildren", parentID)
	ret0, _ := ret[0].([]shared.Agent)
	return ret0
}

// GetChildren indicates an expected call of GetChildren.
func (mr *MockAgentRegistryMockRecorder) GetChildren(parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildren", reflect.TypeOf((*MockAgentRegistry)(nil).GetChildren), parentID)
}

// GetParent mocks base method.
func (m *MockAgentRegistry) GetParent(agentID uuid.UUID) (shared.Agent, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParent", agentID)
	ret0, _ := ret[0].(shared.Agent)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetParent indicates an expected call of GetParent.
func (mr *MockAgentRegistryMockRecorder) GetParent(agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParent", reflect.TypeOf((*MockAgentRegistry)(nil).GetParent), agentID)
}

// GetSubAgentCount mocks base method.
func (m *MockAgentRegistry) GetSubAgentCount(parentID uuid.UUID) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubAgentCount", parentID)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetSubAgentCount indicates an expected call of GetSubAgentCount.
func (mr *MockAgentRegistryMockRecorder) GetSubAgentCount(parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubAgentCount", reflect.TypeOf((*MockAgentRegistry)(nil).GetSubAgentCount), parentID)
}

// GetTotalAgentCount mocks base method.
func (m *MockAgentRegistry) GetTotalAgentCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAgentCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetTotalAgentCount indicates an expected call of GetTotalAgentCount.
func (mr *MockAgentRegistryMockRecorder) GetTotalAgentCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAgentCount", reflect.TypeOf((*MockAgentRegistry)(nil).GetTotalAgentCount))
}

// IsDirectParent mocks base method.
func (m *MockAgentRegistry) IsDirectParent(callerID, targetID uuid.UUID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDirectParent", callerID, targetID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDirectParent indicates an expected call of IsDirectParent.
func (mr *MockAgentRegistryMockRecorder) IsDirectParent(callerID, targetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDirectParent", reflect.TypeOf((*MockAgentRegistry)(nil).IsDirectParent), callerID, targetID)
}

// ListAll mocks base method.
func (m *MockAgentRegistry) ListAll() map[uuid.UUID]shared.Agent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll")
	ret0, _ := ret[0].(map[uuid.UUID]shared.Agent)
	return ret0
}

// ListAll indicates an expected call of ListAll.
func (mr *MockAgentRegistryMockRecorder) ListAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockAgentRegistry)(nil).ListAll))
}

// Register mocks base method.
func (m *MockAgentRegistry) Register(agent shared.Agent, config *shared.AgentConfig, cancel ...context.CancelFunc) error {
	m.ctrl.T.Helper()
	varargs := []any{agent, config}
	for _, a := range cancel {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Register", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockAgentRegistryMockRecorder) Register(agent, config any, cancel ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{agent, config}, cancel...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAgentRegistry)(nil).Register), varargs...)
}

// SetCancelFunc mocks base method.
func (m *MockAgentRegistry) SetCancelFunc(agentID uuid.UUID, cancel context.CancelFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCancelFunc", agentID, cancel)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCancelFunc indicates an expected call of SetCancelFunc.
func (mr *MockAgentRegistryMockRecorder) SetCancelFunc(agentID, cancel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCancelFunc", reflect.TypeOf((*MockAgentRegistry)(nil).SetCancelFunc), agentID, cancel)
}

// StoreAgentResult mocks base method.
func (m *MockAgentRegistry) StoreAgentResult(result shared.AgentResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreAgentResult", result)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreAgentResult indicates an expected call of StoreAgentResult.
func (mr *MockAgentRegistryMockRecorder) StoreAgentResult(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreAgentResult", reflect.TypeOf((*MockAgentRegistry)(nil).StoreAgentResult), result)
}

// Unregister mocks base method.
func (m *MockAgentRegistry) Unregister(agentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unregister", agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unregister indicates an expected call of Unregister.
func (mr *MockAgentRegistryMockRecorder) Unregister(agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockAgentRegistry)(nil).Unregister), agentID)
}

// WaitForAgent mocks base method.
func (m *MockAgentRegistry) WaitForAgent(ctx context.Context, agentID uuid.UUID, timeout time.Duration) (*shared.AgentResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForAgent", ctx, agentID, timeout)
	ret0, _ := ret[0].(*shared.AgentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitForAgent indicates an expected call of WaitForAgent.
func (mr *MockAgentRegistryMockRecorder) WaitForAgent(ctx, agentID, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForAgent", reflect.TypeOf((*MockAgentRegistry)(nil).WaitForAgent), ctx, agentID, timeout)
}
