// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/denkhaus/gollum/pkg/session/persistence/ent/message"
	"github.com/denkhaus/gollum/pkg/session/persistence/ent/schema"
	"github.com/denkhaus/gollum/pkg/session/persistence/ent/session"
	"github.com/denkhaus/gollum/pkg/session/persistence/ent/supervisorconfig"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescTimestamp is the schema descriptor for timestamp field.
	messageDescTimestamp := messageFields[4].Descriptor()
	// message.DefaultTimestamp holds the default value on creation for the timestamp field.
	message.DefaultTimestamp = messageDescTimestamp.Default.(func() time.Time)
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageFields[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCwd is the schema descriptor for cwd field.
	sessionDescCwd := sessionFields[4].Descriptor()
	// session.DefaultCwd holds the default value on creation for the cwd field.
	session.DefaultCwd = sessionDescCwd.Default.(string)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[5].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionFields[6].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	supervisorconfigFields := schema.SupervisorConfig{}.Fields()
	_ = supervisorconfigFields
	// supervisorconfigDescLlmModel is the schema descriptor for llm_model field.
	supervisorconfigDescLlmModel := supervisorconfigFields[2].Descriptor()
	// supervisorconfig.DefaultLlmModel holds the default value on creation for the llm_model field.
	supervisorconfig.DefaultLlmModel = supervisorconfigDescLlmModel.Default.(string)
	// supervisorconfigDescLlmProvider is the schema descriptor for llm_provider field.
	supervisorconfigDescLlmProvider := supervisorconfigFields[3].Descriptor()
	// supervisorconfig.DefaultLlmProvider holds the default value on creation for the llm_provider field.
	supervisorconfig.DefaultLlmProvider = supervisorconfigDescLlmProvider.Default.(string)
	// supervisorconfigDescTemperature is the schema descriptor for temperature field.
	supervisorconfigDescTemperature := supervisorconfigFields[4].Descriptor()
	// supervisorconfig.DefaultTemperature holds the default value on creation for the temperature field.
	supervisorconfig.DefaultTemperature = supervisorconfigDescTemperature.Default.(float32)
	// supervisorconfigDescMaxTokens is the schema descriptor for max_tokens field.
	supervisorconfigDescMaxTokens := supervisorconfigFields[5].Descriptor()
	// supervisorconfig.DefaultMaxTokens holds the default value on creation for the max_tokens field.
	supervisorconfig.DefaultMaxTokens = supervisorconfigDescMaxTokens.Default.(int)
	// supervisorconfigDescID is the schema descriptor for id field.
	supervisorconfigDescID := supervisorconfigFields[0].Descriptor()
	// supervisorconfig.DefaultID holds the default value on creation for the id field.
	supervisorconfig.DefaultID = supervisorconfigDescID.Default.(func() uuid.UUID)
}
