// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/denkhaus/gollum/pkg/session/persistence/ent/session"
	"github.com/denkhaus/gollum/pkg/session/persistence/ent/supervisorconfig"
	"github.com/google/uuid"
)

// SupervisorConfig is the model entity for the SupervisorConfig schema.
type SupervisorConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID uuid.UUID `json:"session_id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Temperature holds the value of the "temperature" field.
	Temperature float32 `json:"temperature,omitempty"`
	// MaxTokens holds the value of the "max_tokens" field.
	MaxTokens int `json:"max_tokens,omitempty"`
	// SystemPrompt holds the value of the "system_prompt" field.
	SystemPrompt string `json:"system_prompt,omitempty"`
	// ConfigJSON holds the value of the "config_json" field.
	ConfigJSON map[string]interface{} `json:"config_json,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SupervisorConfigQuery when eager-loading is set.
	Edges        SupervisorConfigEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SupervisorConfigEdges holds the relations/edges for other nodes in the graph.
type SupervisorConfigEdges struct {
	// Session holds the value of the session edge.
	Session *Session `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupervisorConfigEdges) SessionOrErr() (*Session, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: session.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupervisorConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case supervisorconfig.FieldConfigJSON:
			values[i] = new([]byte)
		case supervisorconfig.FieldTemperature:
			values[i] = new(sql.NullFloat64)
		case supervisorconfig.FieldMaxTokens:
			values[i] = new(sql.NullInt64)
		case supervisorconfig.FieldModel, supervisorconfig.FieldSystemPrompt:
			values[i] = new(sql.NullString)
		case supervisorconfig.FieldID, supervisorconfig.FieldSessionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupervisorConfig fields.
func (_m *SupervisorConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supervisorconfig.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case supervisorconfig.FieldSessionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value != nil {
				_m.SessionID = *value
			}
		case supervisorconfig.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case supervisorconfig.FieldTemperature:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field temperature", values[i])
			} else if value.Valid {
				_m.Temperature = float32(value.Float64)
			}
		case supervisorconfig.FieldMaxTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_tokens", values[i])
			} else if value.Valid {
				_m.MaxTokens = int(value.Int64)
			}
		case supervisorconfig.FieldSystemPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field system_prompt", values[i])
			} else if value.Valid {
				_m.SystemPrompt = value.String
			}
		case supervisorconfig.FieldConfigJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ConfigJSON); err != nil {
					return fmt.Errorf("unmarshal field config_json: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SupervisorConfig.
// This includes values selected through modifiers, order, etc.
func (_m *SupervisorConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the SupervisorConfig entity.
func (_m *SupervisorConfig) QuerySession() *SessionQuery {
	return NewSupervisorConfigClient(_m.config).QuerySession(_m)
}

// Update returns a builder for updating this SupervisorConfig.
// Note that you need to call SupervisorConfig.Unwrap() before calling this method if this SupervisorConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SupervisorConfig) Update() *SupervisorConfigUpdateOne {
	return NewSupervisorConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SupervisorConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SupervisorConfig) Unwrap() *SupervisorConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupervisorConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SupervisorConfig) String() string {
	var builder strings.Builder
	builder.WriteString("SupervisorConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionID))
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("temperature=")
	builder.WriteString(fmt.Sprintf("%v", _m.Temperature))
	builder.WriteString(", ")
	builder.WriteString("max_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxTokens))
	builder.WriteString(", ")
	builder.WriteString("system_prompt=")
	builder.WriteString(_m.SystemPrompt)
	builder.WriteString(", ")
	builder.WriteString("config_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfigJSON))
	builder.WriteByte(')')
	return builder.String()
}

// SupervisorConfigs is a parsable slice of SupervisorConfig.
type SupervisorConfigs []*SupervisorConfig
