// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/denkhaus/gollum/pkg/session/persistence/ent/session"
	"github.com/denkhaus/gollum/pkg/session/persistence/ent/supervisorconfig"
	"github.com/google/uuid"
)

// SupervisorConfigCreate is the builder for creating a SupervisorConfig entity.
type SupervisorConfigCreate struct {
	config
	mutation *SupervisorConfigMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *SupervisorConfigCreate) SetSessionID(v uuid.UUID) *SupervisorConfigCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *SupervisorConfigCreate) SetModel(v string) *SupervisorConfigCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *SupervisorConfigCreate) SetNillableModel(v *string) *SupervisorConfigCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetTemperature sets the "temperature" field.
func (_c *SupervisorConfigCreate) SetTemperature(v float32) *SupervisorConfigCreate {
	_c.mutation.SetTemperature(v)
	return _c
}

// SetNillableTemperature sets the "temperature" field if the given value is not nil.
func (_c *SupervisorConfigCreate) SetNillableTemperature(v *float32) *SupervisorConfigCreate {
	if v != nil {
		_c.SetTemperature(*v)
	}
	return _c
}

// SetMaxTokens sets the "max_tokens" field.
func (_c *SupervisorConfigCreate) SetMaxTokens(v int) *SupervisorConfigCreate {
	_c.mutation.SetMaxTokens(v)
	return _c
}

// SetNillableMaxTokens sets the "max_tokens" field if the given value is not nil.
func (_c *SupervisorConfigCreate) SetNillableMaxTokens(v *int) *SupervisorConfigCreate {
	if v != nil {
		_c.SetMaxTokens(*v)
	}
	return _c
}

// SetSystemPrompt sets the "system_prompt" field.
func (_c *SupervisorConfigCreate) SetSystemPrompt(v string) *SupervisorConfigCreate {
	_c.mutation.SetSystemPrompt(v)
	return _c
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_c *SupervisorConfigCreate) SetNillableSystemPrompt(v *string) *SupervisorConfigCreate {
	if v != nil {
		_c.SetSystemPrompt(*v)
	}
	return _c
}

// SetConfigJSON sets the "config_json" field.
func (_c *SupervisorConfigCreate) SetConfigJSON(v map[string]interface{}) *SupervisorConfigCreate {
	_c.mutation.SetConfigJSON(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SupervisorConfigCreate) SetID(v uuid.UUID) *SupervisorConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SupervisorConfigCreate) SetNillableID(v *uuid.UUID) *SupervisorConfigCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetSession sets the "session" edge to the Session entity.
func (_c *SupervisorConfigCreate) SetSession(v *Session) *SupervisorConfigCreate {
	return _c.SetSessionID(v.ID)
}

// Mutation returns the SupervisorConfigMutation object of the builder.
func (_c *SupervisorConfigCreate) Mutation() *SupervisorConfigMutation {
	return _c.mutation
}

// Save creates the SupervisorConfig in the database.
func (_c *SupervisorConfigCreate) Save(ctx context.Context) (*SupervisorConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupervisorConfigCreate) SaveX(ctx context.Context) *SupervisorConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupervisorConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupervisorConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupervisorConfigCreate) defaults() {
	if _, ok := _c.mutation.Model(); !ok {
		v := supervisorconfig.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.Temperature(); !ok {
		v := supervisorconfig.DefaultTemperature
		_c.mutation.SetTemperature(v)
	}
	if _, ok := _c.mutation.MaxTokens(); !ok {
		v := supervisorconfig.DefaultMaxTokens
		_c.mutation.SetMaxTokens(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := supervisorconfig.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupervisorConfigCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "SupervisorConfig.session_id"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "SupervisorConfig.model"`)}
	}
	if _, ok := _c.mutation.Temperature(); !ok {
		return &ValidationError{Name: "temperature", err: errors.New(`ent: missing required field "SupervisorConfig.temperature"`)}
	}
	if _, ok := _c.mutation.MaxTokens(); !ok {
		return &ValidationError{Name: "max_tokens", err: errors.New(`ent: missing required field "SupervisorConfig.max_tokens"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "SupervisorConfig.session"`)}
	}
	return nil
}

func (_c *SupervisorConfigCreate) sqlSave(ctx context.Context) (*SupervisorConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupervisorConfigCreate) createSpec() (*SupervisorConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &SupervisorConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supervisorconfig.Table, sqlgraph.NewFieldSpec(supervisorconfig.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(supervisorconfig.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Temperature(); ok {
		_spec.SetField(supervisorconfig.FieldTemperature, field.TypeFloat32, value)
		_node.Temperature = value
	}
	if value, ok := _c.mutation.MaxTokens(); ok {
		_spec.SetField(supervisorconfig.FieldMaxTokens, field.TypeInt, value)
		_node.MaxTokens = value
	}
	if value, ok := _c.mutation.SystemPrompt(); ok {
		_spec.SetField(supervisorconfig.FieldSystemPrompt, field.TypeString, value)
		_node.SystemPrompt = value
	}
	if value, ok := _c.mutation.ConfigJSON(); ok {
		_spec.SetField(supervisorconfig.FieldConfigJSON, field.TypeJSON, value)
		_node.ConfigJSON = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   supervisorconfig.SessionTable,
			Columns: []string{supervisorconfig.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SupervisorConfigCreateBulk is the builder for creating many SupervisorConfig entities in bulk.
type SupervisorConfigCreateBulk struct {
	config
	err      error
	builders []*SupervisorConfigCreate
}

// Save creates the SupervisorConfig entities in the database.
func (_c *SupervisorConfigCreateBulk) Save(ctx context.Context) ([]*SupervisorConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SupervisorConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupervisorConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupervisorConfigCreateBulk) SaveX(ctx context.Context) []*SupervisorConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupervisorConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupervisorConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
