// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/denkhaus/gollum/pkg/session/persistence/ent/predicate"
	"github.com/denkhaus/gollum/pkg/session/persistence/ent/session"
	"github.com/denkhaus/gollum/pkg/session/persistence/ent/supervisorconfig"
	"github.com/google/uuid"
)

// SupervisorConfigUpdate is the builder for updating SupervisorConfig entities.
type SupervisorConfigUpdate struct {
	config
	hooks    []Hook
	mutation *SupervisorConfigMutation
}

// Where appends a list predicates to the SupervisorConfigUpdate builder.
func (_u *SupervisorConfigUpdate) Where(ps ...predicate.SupervisorConfig) *SupervisorConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *SupervisorConfigUpdate) SetSessionID(v uuid.UUID) *SupervisorConfigUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *SupervisorConfigUpdate) SetNillableSessionID(v *uuid.UUID) *SupervisorConfigUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *SupervisorConfigUpdate) SetModel(v string) *SupervisorConfigUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *SupervisorConfigUpdate) SetNillableModel(v *string) *SupervisorConfigUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetTemperature sets the "temperature" field.
func (_u *SupervisorConfigUpdate) SetTemperature(v float32) *SupervisorConfigUpdate {
	_u.mutation.ResetTemperature()
	_u.mutation.SetTemperature(v)
	return _u
}

// SetNillableTemperature sets the "temperature" field if the given value is not nil.
func (_u *SupervisorConfigUpdate) SetNillableTemperature(v *float32) *SupervisorConfigUpdate {
	if v != nil {
		_u.SetTemperature(*v)
	}
	return _u
}

// AddTemperature adds value to the "temperature" field.
func (_u *SupervisorConfigUpdate) AddTemperature(v float32) *SupervisorConfigUpdate {
	_u.mutation.AddTemperature(v)
	return _u
}

// SetMaxTokens sets the "max_tokens" field.
func (_u *SupervisorConfigUpdate) SetMaxTokens(v int) *SupervisorConfigUpdate {
	_u.mutation.ResetMaxTokens()
	_u.mutation.SetMaxTokens(v)
	return _u
}

// SetNillableMaxTokens sets the "max_tokens" field if the given value is not nil.
func (_u *SupervisorConfigUpdate) SetNillableMaxTokens(v *int) *SupervisorConfigUpdate {
	if v != nil {
		_u.SetMaxTokens(*v)
	}
	return _u
}

// AddMaxTokens adds value to the "max_tokens" field.
func (_u *SupervisorConfigUpdate) AddMaxTokens(v int) *SupervisorConfigUpdate {
	_u.mutation.AddMaxTokens(v)
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *SupervisorConfigUpdate) SetSystemPrompt(v string) *SupervisorConfigUpdate {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *SupervisorConfigUpdate) SetNillableSystemPrompt(v *string) *SupervisorConfigUpdate {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (_u *SupervisorConfigUpdate) ClearSystemPrompt() *SupervisorConfigUpdate {
	_u.mutation.ClearSystemPrompt()
	return _u
}

// SetConfigJSON sets the "config_json" field.
func (_u *SupervisorConfigUpdate) SetConfigJSON(v map[string]interface{}) *SupervisorConfigUpdate {
	_u.mutation.SetConfigJSON(v)
	return _u
}

// ClearConfigJSON clears the value of the "config_json" field.
func (_u *SupervisorConfigUpdate) ClearConfigJSON() *SupervisorConfigUpdate {
	_u.mutation.ClearConfigJSON()
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *SupervisorConfigUpdate) SetSession(v *Session) *SupervisorConfigUpdate {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the SupervisorConfigMutation object of the builder.
func (_u *SupervisorConfigUpdate) Mutation() *SupervisorConfigMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *SupervisorConfigUpdate) ClearSession() *SupervisorConfigUpdate {
	_u.mutation.ClearSession()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupervisorConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupervisorConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupervisorConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupervisorConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupervisorConfigUpdate) check() error {
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupervisorConfig.session"`)
	}
	return nil
}

func (_u *SupervisorConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supervisorconfig.Table, supervisorconfig.Columns, sqlgraph.NewFieldSpec(supervisorconfig.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(supervisorconfig.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Temperature(); ok {
		_spec.SetField(supervisorconfig.FieldTemperature, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedTemperature(); ok {
		_spec.AddField(supervisorconfig.FieldTemperature, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.MaxTokens(); ok {
		_spec.SetField(supervisorconfig.FieldMaxTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTokens(); ok {
		_spec.AddField(supervisorconfig.FieldMaxTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(supervisorconfig.FieldSystemPrompt, field.TypeString, value)
	}
	if _u.mutation.SystemPromptCleared() {
		_spec.ClearField(supervisorconfig.FieldSystemPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.ConfigJSON(); ok {
		_spec.SetField(supervisorconfig.FieldConfigJSON, field.TypeJSON, value)
	}
	if _u.mutation.ConfigJSONCleared() {
		_spec.ClearField(supervisorconfig.FieldConfigJSON, field.TypeJSON)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   supervisorconfig.SessionTable,
			Columns: []string{supervisorconfig.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   supervisorconfig.SessionTable,
			Columns: []string{supervisorconfig.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supervisorconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupervisorConfigUpdateOne is the builder for updating a single SupervisorConfig entity.
type SupervisorConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupervisorConfigMutation
}

// SetSessionID sets the "session_id" field.
func (_u *SupervisorConfigUpdateOne) SetSessionID(v uuid.UUID) *SupervisorConfigUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *SupervisorConfigUpdateOne) SetNillableSessionID(v *uuid.UUID) *SupervisorConfigUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *SupervisorConfigUpdateOne) SetModel(v string) *SupervisorConfigUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *SupervisorConfigUpdateOne) SetNillableModel(v *string) *SupervisorConfigUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetTemperature sets the "temperature" field.
func (_u *SupervisorConfigUpdateOne) SetTemperature(v float32) *SupervisorConfigUpdateOne {
	_u.mutation.ResetTemperature()
	_u.mutation.SetTemperature(v)
	return _u
}

// SetNillableTemperature sets the "temperature" field if the given value is not nil.
func (_u *SupervisorConfigUpdateOne) SetNillableTemperature(v *float32) *SupervisorConfigUpdateOne {
	if v != nil {
		_u.SetTemperature(*v)
	}
	return _u
}

// AddTemperature adds value to the "temperature" field.
func (_u *SupervisorConfigUpdateOne) AddTemperature(v float32) *SupervisorConfigUpdateOne {
	_u.mutation.AddTemperature(v)
	return _u
}

// SetMaxTokens sets the "max_tokens" field.
func (_u *SupervisorConfigUpdateOne) SetMaxTokens(v int) *SupervisorConfigUpdateOne {
	_u.mutation.ResetMaxTokens()
	_u.mutation.SetMaxTokens(v)
	return _u
}

// SetNillableMaxTokens sets the "max_tokens" field if the given value is not nil.
func (_u *SupervisorConfigUpdateOne) SetNillableMaxTokens(v *int) *SupervisorConfigUpdateOne {
	if v != nil {
		_u.SetMaxTokens(*v)
	}
	return _u
}

// AddMaxTokens adds value to the "max_tokens" field.
func (_u *SupervisorConfigUpdateOne) AddMaxTokens(v int) *SupervisorConfigUpdateOne {
	_u.mutation.AddMaxTokens(v)
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *SupervisorConfigUpdateOne) SetSystemPrompt(v string) *SupervisorConfigUpdateOne {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *SupervisorConfigUpdateOne) SetNillableSystemPrompt(v *string) *SupervisorConfigUpdateOne {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (_u *SupervisorConfigUpdateOne) ClearSystemPrompt() *SupervisorConfigUpdateOne {
	_u.mutation.ClearSystemPrompt()
	return _u
}

// SetConfigJSON sets the "config_json" field.
func (_u *SupervisorConfigUpdateOne) SetConfigJSON(v map[string]interface{}) *SupervisorConfigUpdateOne {
	_u.mutation.SetConfigJSON(v)
	return _u
}

// ClearConfigJSON clears the value of the "config_json" field.
func (_u *SupervisorConfigUpdateOne) ClearConfigJSON() *SupervisorConfigUpdateOne {
	_u.mutation.ClearConfigJSON()
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *SupervisorConfigUpdateOne) SetSession(v *Session) *SupervisorConfigUpdateOne {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the SupervisorConfigMutation object of the builder.
func (_u *SupervisorConfigUpdateOne) Mutation() *SupervisorConfigMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *SupervisorConfigUpdateOne) ClearSession() *SupervisorConfigUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// Where appends a list predicates to the SupervisorConfigUpdate builder.
func (_u *SupervisorConfigUpdateOne) Where(ps ...predicate.SupervisorConfig) *SupervisorConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupervisorConfigUpdateOne) Select(field string, fields ...string) *SupervisorConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupervisorConfig entity.
func (_u *SupervisorConfigUpdateOne) Save(ctx context.Context) (*SupervisorConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupervisorConfigUpdateOne) SaveX(ctx context.Context) *SupervisorConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupervisorConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupervisorConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupervisorConfigUpdateOne) check() error {
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupervisorConfig.session"`)
	}
	return nil
}

func (_u *SupervisorConfigUpdateOne) sqlSave(ctx context.Context) (_node *SupervisorConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supervisorconfig.Table, supervisorconfig.Columns, sqlgraph.NewFieldSpec(supervisorconfig.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupervisorConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supervisorconfig.FieldID)
		for _, f := range fields {
			if !supervisorconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supervisorconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(supervisorconfig.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Temperature(); ok {
		_spec.SetField(supervisorconfig.FieldTemperature, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedTemperature(); ok {
		_spec.AddField(supervisorconfig.FieldTemperature, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.MaxTokens(); ok {
		_spec.SetField(supervisorconfig.FieldMaxTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTokens(); ok {
		_spec.AddField(supervisorconfig.FieldMaxTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(supervisorconfig.FieldSystemPrompt, field.TypeString, value)
	}
	if _u.mutation.SystemPromptCleared() {
		_spec.ClearField(supervisorconfig.FieldSystemPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.ConfigJSON(); ok {
		_spec.SetField(supervisorconfig.FieldConfigJSON, field.TypeJSON, value)
	}
	if _u.mutation.ConfigJSONCleared() {
		_spec.ClearField(supervisorconfig.FieldConfigJSON, field.TypeJSON)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   supervisorconfig.SessionTable,
			Columns: []string{supervisorconfig.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   supervisorconfig.SessionTable,
			Columns: []string{supervisorconfig.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupervisorConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supervisorconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
