// Code generated by MockGen. DO NOT EDIT.
// Source: /home/denkhaus/dev/gomodules/gollum/pkg/command/types.go
//
// Generated by this command:
//
//	mockgen -source=/home/denkhaus/dev/gomodules/gollum/pkg/command/types.go -destination=/home/denkhaus/dev/gomodules/gollum/pkg/command/manager_mock.go -package=command github.com/denkhaus/gollum/pkg/command Manager
//

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockManager) Execute(ctx context.Context, sessionID, input string) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, sessionID, input)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Execute indicates an expected call of Execute.
func (mr *MockManagerMockRecorder) Execute(ctx, sessionID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockManager)(nil).Execute), ctx, sessionID, input)
}

// IsCommand mocks base method.
func (m *MockManager) IsCommand(input string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCommand", input)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCommand indicates an expected call of IsCommand.
func (mr *MockManagerMockRecorder) IsCommand(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCommand", reflect.TypeOf((*MockManager)(nil).IsCommand), input)
}

// List mocks base method.
func (m *MockManager) List() []Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]Command)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockManagerMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockManager)(nil).List))
}

// Register mocks base method.
func (m *MockManager) Register(cmd Command) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockManagerMockRecorder) Register(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockManager)(nil).Register), cmd)
}

// Unregister mocks base method.
func (m *MockManager) Unregister(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unregister", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unregister indicates an expected call of Unregister.
func (mr *MockManagerMockRecorder) Unregister(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockManager)(nil).Unregister), name)
}
