// Code generated by ent, DO NOT EDIT.

package supervisorconfig

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/denkhaus/gollum/pkg/session/persistence/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldLTE(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v uuid.UUID) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEQ(FieldSessionID, v))
}

// LlmModel applies equality check predicate on the "llm_model" field. It's identical to LlmModelEQ.
func LlmModel(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEQ(FieldLlmModel, v))
}

// LlmProvider applies equality check predicate on the "llm_provider" field. It's identical to LlmProviderEQ.
func LlmProvider(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEQ(FieldLlmProvider, v))
}

// Temperature applies equality check predicate on the "temperature" field. It's identical to TemperatureEQ.
func Temperature(v float32) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEQ(FieldTemperature, v))
}

// MaxTokens applies equality check predicate on the "max_tokens" field. It's identical to MaxTokensEQ.
func MaxTokens(v int) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEQ(FieldMaxTokens, v))
}

// SystemPrompt applies equality check predicate on the "system_prompt" field. It's identical to SystemPromptEQ.
func SystemPrompt(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEQ(FieldSystemPrompt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v uuid.UUID) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v uuid.UUID) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...uuid.UUID) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...uuid.UUID) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNotIn(FieldSessionID, vs...))
}

// LlmModelEQ applies the EQ predicate on the "llm_model" field.
func LlmModelEQ(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEQ(FieldLlmModel, v))
}

// LlmModelNEQ applies the NEQ predicate on the "llm_model" field.
func LlmModelNEQ(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNEQ(FieldLlmModel, v))
}

// LlmModelIn applies the In predicate on the "llm_model" field.
func LlmModelIn(vs ...string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldIn(FieldLlmModel, vs...))
}

// LlmModelNotIn applies the NotIn predicate on the "llm_model" field.
func LlmModelNotIn(vs ...string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNotIn(FieldLlmModel, vs...))
}

// LlmModelGT applies the GT predicate on the "llm_model" field.
func LlmModelGT(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldGT(FieldLlmModel, v))
}

// LlmModelGTE applies the GTE predicate on the "llm_model" field.
func LlmModelGTE(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldGTE(FieldLlmModel, v))
}

// LlmModelLT applies the LT predicate on the "llm_model" field.
func LlmModelLT(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldLT(FieldLlmModel, v))
}

// LlmModelLTE applies the LTE predicate on the "llm_model" field.
func LlmModelLTE(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldLTE(FieldLlmModel, v))
}

// LlmModelContains applies the Contains predicate on the "llm_model" field.
func LlmModelContains(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldContains(FieldLlmModel, v))
}

// LlmModelHasPrefix applies the HasPrefix predicate on the "llm_model" field.
func LlmModelHasPrefix(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldHasPrefix(FieldLlmModel, v))
}

// LlmModelHasSuffix applies the HasSuffix predicate on the "llm_model" field.
func LlmModelHasSuffix(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldHasSuffix(FieldLlmModel, v))
}

// LlmModelEqualFold applies the EqualFold predicate on the "llm_model" field.
func LlmModelEqualFold(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEqualFold(FieldLlmModel, v))
}

// LlmModelContainsFold applies the ContainsFold predicate on the "llm_model" field.
func LlmModelContainsFold(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldContainsFold(FieldLlmModel, v))
}

// LlmProviderEQ applies the EQ predicate on the "llm_provider" field.
func LlmProviderEQ(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEQ(FieldLlmProvider, v))
}

// LlmProviderNEQ applies the NEQ predicate on the "llm_provider" field.
func LlmProviderNEQ(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNEQ(FieldLlmProvider, v))
}

// LlmProviderIn applies the In predicate on the "llm_provider" field.
func LlmProviderIn(vs ...string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldIn(FieldLlmProvider, vs...))
}

// LlmProviderNotIn applies the NotIn predicate on the "llm_provider" field.
func LlmProviderNotIn(vs ...string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNotIn(FieldLlmProvider, vs...))
}

// LlmProviderGT applies the GT predicate on the "llm_provider" field.
func LlmProviderGT(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldGT(FieldLlmProvider, v))
}

// LlmProviderGTE applies the GTE predicate on the "llm_provider" field.
func LlmProviderGTE(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldGTE(FieldLlmProvider, v))
}

// LlmProviderLT applies the LT predicate on the "llm_provider" field.
func LlmProviderLT(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldLT(FieldLlmProvider, v))
}

// LlmProviderLTE applies the LTE predicate on the "llm_provider" field.
func LlmProviderLTE(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldLTE(FieldLlmProvider, v))
}

// LlmProviderContains applies the Contains predicate on the "llm_provider" field.
func LlmProviderContains(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldContains(FieldLlmProvider, v))
}

// LlmProviderHasPrefix applies the HasPrefix predicate on the "llm_provider" field.
func LlmProviderHasPrefix(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldHasPrefix(FieldLlmProvider, v))
}

// LlmProviderHasSuffix applies the HasSuffix predicate on the "llm_provider" field.
func LlmProviderHasSuffix(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldHasSuffix(FieldLlmProvider, v))
}

// LlmProviderEqualFold applies the EqualFold predicate on the "llm_provider" field.
func LlmProviderEqualFold(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEqualFold(FieldLlmProvider, v))
}

// LlmProviderContainsFold applies the ContainsFold predicate on the "llm_provider" field.
func LlmProviderContainsFold(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldContainsFold(FieldLlmProvider, v))
}

// TemperatureEQ applies the EQ predicate on the "temperature" field.
func TemperatureEQ(v float32) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEQ(FieldTemperature, v))
}

// TemperatureNEQ applies the NEQ predicate on the "temperature" field.
func TemperatureNEQ(v float32) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNEQ(FieldTemperature, v))
}

// TemperatureIn applies the In predicate on the "temperature" field.
func TemperatureIn(vs ...float32) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldIn(FieldTemperature, vs...))
}

// TemperatureNotIn applies the NotIn predicate on the "temperature" field.
func TemperatureNotIn(vs ...float32) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNotIn(FieldTemperature, vs...))
}

// TemperatureGT applies the GT predicate on the "temperature" field.
func TemperatureGT(v float32) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldGT(FieldTemperature, v))
}

// TemperatureGTE applies the GTE predicate on the "temperature" field.
func TemperatureGTE(v float32) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldGTE(FieldTemperature, v))
}

// TemperatureLT applies the LT predicate on the "temperature" field.
func TemperatureLT(v float32) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldLT(FieldTemperature, v))
}

// TemperatureLTE applies the LTE predicate on the "temperature" field.
func TemperatureLTE(v float32) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldLTE(FieldTemperature, v))
}

// MaxTokensEQ applies the EQ predicate on the "max_tokens" field.
func MaxTokensEQ(v int) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEQ(FieldMaxTokens, v))
}

// MaxTokensNEQ applies the NEQ predicate on the "max_tokens" field.
func MaxTokensNEQ(v int) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNEQ(FieldMaxTokens, v))
}

// MaxTokensIn applies the In predicate on the "max_tokens" field.
func MaxTokensIn(vs ...int) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldIn(FieldMaxTokens, vs...))
}

// MaxTokensNotIn applies the NotIn predicate on the "max_tokens" field.
func MaxTokensNotIn(vs ...int) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNotIn(FieldMaxTokens, vs...))
}

// MaxTokensGT applies the GT predicate on the "max_tokens" field.
func MaxTokensGT(v int) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldGT(FieldMaxTokens, v))
}

// MaxTokensGTE applies the GTE predicate on the "max_tokens" field.
func MaxTokensGTE(v int) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldGTE(FieldMaxTokens, v))
}

// MaxTokensLT applies the LT predicate on the "max_tokens" field.
func MaxTokensLT(v int) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldLT(FieldMaxTokens, v))
}

// MaxTokensLTE applies the LTE predicate on the "max_tokens" field.
func MaxTokensLTE(v int) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldLTE(FieldMaxTokens, v))
}

// SystemPromptEQ applies the EQ predicate on the "system_prompt" field.
func SystemPromptEQ(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEQ(FieldSystemPrompt, v))
}

// SystemPromptNEQ applies the NEQ predicate on the "system_prompt" field.
func SystemPromptNEQ(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNEQ(FieldSystemPrompt, v))
}

// SystemPromptIn applies the In predicate on the "system_prompt" field.
func SystemPromptIn(vs ...string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldIn(FieldSystemPrompt, vs...))
}

// SystemPromptNotIn applies the NotIn predicate on the "system_prompt" field.
func SystemPromptNotIn(vs ...string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNotIn(FieldSystemPrompt, vs...))
}

// SystemPromptGT applies the GT predicate on the "system_prompt" field.
func SystemPromptGT(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldGT(FieldSystemPrompt, v))
}

// SystemPromptGTE applies the GTE predicate on the "system_prompt" field.
func SystemPromptGTE(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldGTE(FieldSystemPrompt, v))
}

// SystemPromptLT applies the LT predicate on the "system_prompt" field.
func SystemPromptLT(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldLT(FieldSystemPrompt, v))
}

// SystemPromptLTE applies the LTE predicate on the "system_prompt" field.
func SystemPromptLTE(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldLTE(FieldSystemPrompt, v))
}

// SystemPromptContains applies the Contains predicate on the "system_prompt" field.
func SystemPromptContains(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldContains(FieldSystemPrompt, v))
}

// SystemPromptHasPrefix applies the HasPrefix predicate on the "system_prompt" field.
func SystemPromptHasPrefix(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldHasPrefix(FieldSystemPrompt, v))
}

// SystemPromptHasSuffix applies the HasSuffix predicate on the "system_prompt" field.
func SystemPromptHasSuffix(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldHasSuffix(FieldSystemPrompt, v))
}

// SystemPromptIsNil applies the IsNil predicate on the "system_prompt" field.
func SystemPromptIsNil() predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldIsNull(FieldSystemPrompt))
}

// SystemPromptNotNil applies the NotNil predicate on the "system_prompt" field.
func SystemPromptNotNil() predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNotNull(FieldSystemPrompt))
}

// SystemPromptEqualFold applies the EqualFold predicate on the "system_prompt" field.
func SystemPromptEqualFold(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldEqualFold(FieldSystemPrompt, v))
}

// SystemPromptContainsFold applies the ContainsFold predicate on the "system_prompt" field.
func SystemPromptContainsFold(v string) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldContainsFold(FieldSystemPrompt, v))
}

// ConfigJSONIsNil applies the IsNil predicate on the "config_json" field.
func ConfigJSONIsNil() predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldIsNull(FieldConfigJSON))
}

// ConfigJSONNotNil applies the NotNil predicate on the "config_json" field.
func ConfigJSONNotNil() predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.FieldNotNull(FieldConfigJSON))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.SupervisorConfig {
	return predicate.SupervisorConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.Session) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupervisorConfig) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupervisorConfig) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupervisorConfig) predicate.SupervisorConfig {
	return predicate.SupervisorConfig(sql.NotPredicates(p))
}
