// Code generated by "stringer -type=AgentType"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AgentTypeUnknown-0]
	_ = x[AgentTypeSupervisor-1]
	_ = x[AgentTypeSubAgent-2]
}

const _AgentType_name = "AgentTypeUnknownAgentTypeSupervisorAgentTypeSubAgent"

var _AgentType_index = [...]uint8{0, 16, 35, 52}

func (i AgentType) String() string {
	if i < 0 || i >= AgentType(len(_AgentType_index)-1) {
		return "AgentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AgentType_name[_AgentType_index[i]:_AgentType_index[i+1]]
}
