// Code generated by MockGen. DO NOT EDIT.
// Source: shared/factory.go
//
// Generated by this command:
//
//	mockgen -source=shared/factory.go -destination=shared/factory_mock.go -package=shared github.com/denkhaus/gollum/pkg/shared AgentFactory
//

// Package shared is a generated GoMock package.
package shared

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAgentFactory is a mock of AgentFactory interface.
type MockAgentFactory struct {
	ctrl     *gomock.Controller
	recorder *MockAgentFactoryMockRecorder
	isgomock struct{}
}

// MockAgentFactoryMockRecorder is the mock recorder for MockAgentFactory.
type MockAgentFactoryMockRecorder struct {
	mock *MockAgentFactory
}

// NewMockAgentFactory creates a new mock instance.
func NewMockAgentFactory(ctrl *gomock.Controller) *MockAgentFactory {
	mock := &MockAgentFactory{ctrl: ctrl}
	mock.recorder = &MockAgentFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentFactory) EXPECT() *MockAgentFactoryMockRecorder {
	return m.recorder
}

// CreateAgent mocks base method.
func (m *MockAgentFactory) CreateAgent(ctx context.Context, config *AgentConfig) (Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAgent", ctx, config)
	ret0, _ := ret[0].(Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAgent indicates an expected call of CreateAgent.
func (mr *MockAgentFactoryMockRecorder) CreateAgent(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAgent", reflect.TypeOf((*MockAgentFactory)(nil).CreateAgent), ctx, config)
}

// CreateSupervisorAgent mocks base method.
func (m *MockAgentFactory) CreateSupervisorAgent(ctx context.Context) (Agent, *AgentConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSupervisorAgent", ctx)
	ret0, _ := ret[0].(Agent)
	ret1, _ := ret[1].(*AgentConfig)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateSupervisorAgent indicates an expected call of CreateSupervisorAgent.
func (mr *MockAgentFactoryMockRecorder) CreateSupervisorAgent(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSupervisorAgent", reflect.TypeOf((*MockAgentFactory)(nil).CreateSupervisorAgent), ctx)
}
