// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/shared/flows.go
//
// Generated by this command:
//
//	mockgen -source=pkg/shared/flows.go -destination=pkg/shared/flows_mock.go -package=shared github.com/denkhaus/gollum/pkg/shared FlowExecutorInstance
//

// Package shared is a generated GoMock package.
package shared

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFlowContext is a mock of FlowContext interface.
type MockFlowContext struct {
	ctrl     *gomock.Controller
	recorder *MockFlowContextMockRecorder
	isgomock struct{}
}

// MockFlowContextMockRecorder is the mock recorder for MockFlowContext.
type MockFlowContextMockRecorder struct {
	mock *MockFlowContext
}

// NewMockFlowContext creates a new mock instance.
func NewMockFlowContext(ctrl *gomock.Controller) *MockFlowContext {
	mock := &MockFlowContext{ctrl: ctrl}
	mock.recorder = &MockFlowContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowContext) EXPECT() *MockFlowContextMockRecorder {
	return m.recorder
}

// GetAllContextFields mocks base method.
func (m *MockFlowContext) GetAllContextFields() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllContextFields")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetAllContextFields indicates an expected call of GetAllContextFields.
func (mr *MockFlowContextMockRecorder) GetAllContextFields() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllContextFields", reflect.TypeOf((*MockFlowContext)(nil).GetAllContextFields))
}

// GetContextField mocks base method.
func (m *MockFlowContext) GetContextField(name string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContextField", name)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContextField indicates an expected call of GetContextField.
func (mr *MockFlowContextMockRecorder) GetContextField(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContextField", reflect.TypeOf((*MockFlowContext)(nil).GetContextField), name)
}

// GetCurrentState mocks base method.
func (m *MockFlowContext) GetCurrentState() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentState")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCurrentState indicates an expected call of GetCurrentState.
func (mr *MockFlowContextMockRecorder) GetCurrentState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentState", reflect.TypeOf((*MockFlowContext)(nil).GetCurrentState))
}

// GetOutputField mocks base method.
func (m *MockFlowContext) GetOutputField(name string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutputField", name)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutputField indicates an expected call of GetOutputField.
func (mr *MockFlowContextMockRecorder) GetOutputField(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutputField", reflect.TypeOf((*MockFlowContext)(nil).GetOutputField), name)
}

// RequestTransition mocks base method.
func (m *MockFlowContext) RequestTransition(to string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestTransition", to)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestTransition indicates an expected call of RequestTransition.
func (mr *MockFlowContextMockRecorder) RequestTransition(to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestTransition", reflect.TypeOf((*MockFlowContext)(nil).RequestTransition), to)
}

// SetContextField mocks base method.
func (m *MockFlowContext) SetContextField(name string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetContextField", name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetContextField indicates an expected call of SetContextField.
func (mr *MockFlowContextMockRecorder) SetContextField(name, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContextField", reflect.TypeOf((*MockFlowContext)(nil).SetContextField), name, value)
}

// SetOutputField mocks base method.
func (m *MockFlowContext) SetOutputField(name string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOutputField", name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOutputField indicates an expected call of SetOutputField.
func (mr *MockFlowContextMockRecorder) SetOutputField(name, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOutputField", reflect.TypeOf((*MockFlowContext)(nil).SetOutputField), name, value)
}

// ValidateTransition mocks base method.
func (m *MockFlowContext) ValidateTransition(from, to string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTransition", from, to)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateTransition indicates an expected call of ValidateTransition.
func (mr *MockFlowContextMockRecorder) ValidateTransition(from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTransition", reflect.TypeOf((*MockFlowContext)(nil).ValidateTransition), from, to)
}

// MockExecutionContext is a mock of ExecutionContext interface.
type MockExecutionContext struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionContextMockRecorder
	isgomock struct{}
}

// MockExecutionContextMockRecorder is the mock recorder for MockExecutionContext.
type MockExecutionContextMockRecorder struct {
	mock *MockExecutionContext
}

// NewMockExecutionContext creates a new mock instance.
func NewMockExecutionContext(ctrl *gomock.Controller) *MockExecutionContext {
	mock := &MockExecutionContext{ctrl: ctrl}
	mock.recorder = &MockExecutionContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionContext) EXPECT() *MockExecutionContextMockRecorder {
	return m.recorder
}

// EvaluateComputed mocks base method.
func (m *MockExecutionContext) EvaluateComputed() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateComputed")
	ret0, _ := ret[0].(error)
	return ret0
}

// EvaluateComputed indicates an expected call of EvaluateComputed.
func (mr *MockExecutionContextMockRecorder) EvaluateComputed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateComputed", reflect.TypeOf((*MockExecutionContext)(nil).EvaluateComputed))
}

// GetComputedField mocks base method.
func (m *MockExecutionContext) GetComputedField(name string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComputedField", name)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComputedField indicates an expected call of GetComputedField.
func (mr *MockExecutionContextMockRecorder) GetComputedField(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComputedField", reflect.TypeOf((*MockExecutionContext)(nil).GetComputedField), name)
}

// GetContextField mocks base method.
func (m *MockExecutionContext) GetContextField(name string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContextField", name)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContextField indicates an expected call of GetContextField.
func (mr *MockExecutionContextMockRecorder) GetContextField(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContextField", reflect.TypeOf((*MockExecutionContext)(nil).GetContextField), name)
}

// GetError mocks base method.
func (m *MockExecutionContext) GetError() *ErrorContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetError")
	ret0, _ := ret[0].(*ErrorContext)
	return ret0
}

// GetError indicates an expected call of GetError.
func (mr *MockExecutionContextMockRecorder) GetError() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetError", reflect.TypeOf((*MockExecutionContext)(nil).GetError))
}

// GetInput mocks base method.
func (m *MockExecutionContext) GetInput(name string) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInput", name)
	ret0, _ := ret[0].(any)
	return ret0
}

// GetInput indicates an expected call of GetInput.
func (mr *MockExecutionContextMockRecorder) GetInput(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInput", reflect.TypeOf((*MockExecutionContext)(nil).GetInput), name)
}

// GetOutputField mocks base method.
func (m *MockExecutionContext) GetOutputField(name string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutputField", name)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutputField indicates an expected call of GetOutputField.
func (mr *MockExecutionContextMockRecorder) GetOutputField(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutputField", reflect.TypeOf((*MockExecutionContext)(nil).GetOutputField), name)
}

// SetContextField mocks base method.
func (m *MockExecutionContext) SetContextField(name string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetContextField", name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetContextField indicates an expected call of SetContextField.
func (mr *MockExecutionContextMockRecorder) SetContextField(name, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContextField", reflect.TypeOf((*MockExecutionContext)(nil).SetContextField), name, value)
}

// SetError mocks base method.
func (m *MockExecutionContext) SetError(ctx *ErrorContext) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetError", ctx)
}

// SetError indicates an expected call of SetError.
func (mr *MockExecutionContextMockRecorder) SetError(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetError", reflect.TypeOf((*MockExecutionContext)(nil).SetError), ctx)
}

// SetOutputField mocks base method.
func (m *MockExecutionContext) SetOutputField(name string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOutputField", name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOutputField indicates an expected call of SetOutputField.
func (mr *MockExecutionContextMockRecorder) SetOutputField(name, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOutputField", reflect.TypeOf((*MockExecutionContext)(nil).SetOutputField), name, value)
}

// MockFlowExecutorInstance is a mock of FlowExecutorInstance interface.
type MockFlowExecutorInstance struct {
	ctrl     *gomock.Controller
	recorder *MockFlowExecutorInstanceMockRecorder
	isgomock struct{}
}

// MockFlowExecutorInstanceMockRecorder is the mock recorder for MockFlowExecutorInstance.
type MockFlowExecutorInstanceMockRecorder struct {
	mock *MockFlowExecutorInstance
}

// NewMockFlowExecutorInstance creates a new mock instance.
func NewMockFlowExecutorInstance(ctrl *gomock.Controller) *MockFlowExecutorInstance {
	mock := &MockFlowExecutorInstance{ctrl: ctrl}
	mock.recorder = &MockFlowExecutorInstanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowExecutorInstance) EXPECT() *MockFlowExecutorInstanceMockRecorder {
	return m.recorder
}

// GetContext mocks base method.
func (m *MockFlowExecutorInstance) GetContext() ExecutionContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContext")
	ret0, _ := ret[0].(ExecutionContext)
	return ret0
}

// GetContext indicates an expected call of GetContext.
func (mr *MockFlowExecutorInstanceMockRecorder) GetContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContext", reflect.TypeOf((*MockFlowExecutorInstance)(nil).GetContext))
}

// Run mocks base method.
func (m *MockFlowExecutorInstance) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockFlowExecutorInstanceMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockFlowExecutorInstance)(nil).Run))
}

// SetInput mocks base method.
func (m *MockFlowExecutorInstance) SetInput(vals map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetInput", vals)
}

// SetInput indicates an expected call of SetInput.
func (mr *MockFlowExecutorInstanceMockRecorder) SetInput(vals any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInput", reflect.TypeOf((*MockFlowExecutorInstance)(nil).SetInput), vals)
}

// Validate mocks base method.
func (m *MockFlowExecutorInstance) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockFlowExecutorInstanceMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockFlowExecutorInstance)(nil).Validate))
}
