// Code generated by MockGen. DO NOT EDIT.
// Source: ../ui/agent_messenger.go
//
// Generated by this command:
//
//	mockgen -source=../ui/agent_messenger.go -destination=mock_agent_messenger.go -package=mocks github.com/denkhaus/gollum/pkg/ui AgentMessenger
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentMessenger is a mock of AgentMessenger interface.
type MockAgentMessenger struct {
	ctrl     *gomock.Controller
	recorder *MockAgentMessengerMockRecorder
	isgomock struct{}
}

// MockAgentMessengerMockRecorder is the mock recorder for MockAgentMessenger.
type MockAgentMessengerMockRecorder struct {
	mock *MockAgentMessenger
}

// NewMockAgentMessenger creates a new mock instance.
func NewMockAgentMessenger(ctrl *gomock.Controller) *MockAgentMessenger {
	mock := &MockAgentMessenger{ctrl: ctrl}
	mock.recorder = &MockAgentMessengerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentMessenger) EXPECT() *MockAgentMessengerMockRecorder {
	return m.recorder
}

// DisplayAgentMessage mocks base method.
func (m *MockAgentMessenger) DisplayAgentMessage(agentID uuid.UUID, agentRole, message string, isTool bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplayAgentMessage", agentID, agentRole, message, isTool)
}

// DisplayAgentMessage indicates an expected call of DisplayAgentMessage.
func (mr *MockAgentMessengerMockRecorder) DisplayAgentMessage(agentID, agentRole, message, isTool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayAgentMessage", reflect.TypeOf((*MockAgentMessenger)(nil).DisplayAgentMessage), agentID, agentRole, message, isTool)
}

// DisplaySystemInfo mocks base method.
func (m *MockAgentMessenger) DisplaySystemInfo(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplaySystemInfo", message)
}

// DisplaySystemInfo indicates an expected call of DisplaySystemInfo.
func (mr *MockAgentMessengerMockRecorder) DisplaySystemInfo(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplaySystemInfo", reflect.TypeOf((*MockAgentMessenger)(nil).DisplaySystemInfo), message)
}

// DisplayUserMessage mocks base method.
func (m *MockAgentMessenger) DisplayUserMessage(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplayUserMessage", message)
}

// DisplayUserMessage indicates an expected call of DisplayUserMessage.
func (mr *MockAgentMessengerMockRecorder) DisplayUserMessage(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayUserMessage", reflect.TypeOf((*MockAgentMessenger)(nil).DisplayUserMessage), message)
}
