// Code generated by MockGen. DO NOT EDIT.
// Source: ../llm/provider.go
//
// Generated by this command:
//
//	mockgen -source=../llm/provider.go -destination=mock_llm_client_provider.go -package=mocks github.com/denkhaus/gollum/pkg/llm ClientProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	shared "github.com/denkhaus/gollum/pkg/shared"
	gollem "github.com/m-mizutani/gollem"
	gomock "go.uber.org/mock/gomock"
)

// MockClientProvider is a mock of ClientProvider interface.
type MockClientProvider struct {
	ctrl     *gomock.Controller
	recorder *MockClientProviderMockRecorder
	isgomock struct{}
}

// MockClientProviderMockRecorder is the mock recorder for MockClientProvider.
type MockClientProviderMockRecorder struct {
	mock *MockClientProvider
}

// NewMockClientProvider creates a new mock instance.
func NewMockClientProvider(ctrl *gomock.Controller) *MockClientProvider {
	mock := &MockClientProvider{ctrl: ctrl}
	mock.recorder = &MockClientProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientProvider) EXPECT() *MockClientProviderMockRecorder {
	return m.recorder
}

// GetClient mocks base method.
func (m *MockClientProvider) GetClient(ctx context.Context, provider shared.LLMProvider) (gollem.LLMClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ctx, provider)
	ret0, _ := ret[0].(gollem.LLMClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockClientProviderMockRecorder) GetClient(ctx, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockClientProvider)(nil).GetClient), ctx, provider)
}
