// Code generated by MockGen. DO NOT EDIT.
// Source: ../hooks/manager.go
//
// Generated by this command:
//
//	mockgen -source=../hooks/manager.go -destination=mock_hook_manager.go -package=mocks github.com/denkhaus/gollum/pkg/hooks HookManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	hooks "github.com/denkhaus/gollum/pkg/hooks"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockHookManager is a mock of HookManager interface.
type MockHookManager struct {
	ctrl     *gomock.Controller
	recorder *MockHookManagerMockRecorder
	isgomock struct{}
}

// MockHookManagerMockRecorder is the mock recorder for MockHookManager.
type MockHookManagerMockRecorder struct {
	mock *MockHookManager
}

// NewMockHookManager creates a new mock instance.
func NewMockHookManager(ctrl *gomock.Controller) *MockHookManager {
	mock := &MockHookManager{ctrl: ctrl}
	mock.recorder = &MockHookManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHookManager) EXPECT() *MockHookManagerMockRecorder {
	return m.recorder
}

// RegisterHook mocks base method.
func (m *MockHookManager) RegisterHook(fn hooks.HookFunc, meta hooks.HookMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterHook", fn, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterHook indicates an expected call of RegisterHook.
func (mr *MockHookManagerMockRecorder) RegisterHook(fn, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterHook", reflect.TypeOf((*MockHookManager)(nil).RegisterHook), fn, meta)
}

// TriggerHooks mocks base method.
func (m *MockHookManager) TriggerHooks(ctx context.Context, point hooks.HookPoint, hookCtx *hooks.HookContext) hooks.HookResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerHooks", ctx, point, hookCtx)
	ret0, _ := ret[0].(hooks.HookResult)
	return ret0
}

// TriggerHooks indicates an expected call of TriggerHooks.
func (mr *MockHookManagerMockRecorder) TriggerHooks(ctx, point, hookCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerHooks", reflect.TypeOf((*MockHookManager)(nil).TriggerHooks), ctx, point, hookCtx)
}

// UnregisterHook mocks base method.
func (m *MockHookManager) UnregisterHook(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterHook", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// UnregisterHook indicates an expected call of UnregisterHook.
func (mr *MockHookManagerMockRecorder) UnregisterHook(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterHook", reflect.TypeOf((*MockHookManager)(nil).UnregisterHook), name)
}

// WithAgentHooks mocks base method.
func (m *MockHookManager) WithAgentHooks(ctx context.Context, sessionID, agentID uuid.UUID, point hooks.HookPoint, work func() error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithAgentHooks", ctx, sessionID, agentID, point, work)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithAgentHooks indicates an expected call of WithAgentHooks.
func (mr *MockHookManagerMockRecorder) WithAgentHooks(ctx, sessionID, agentID, point, work any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithAgentHooks", reflect.TypeOf((*MockHookManager)(nil).WithAgentHooks), ctx, sessionID, agentID, point, work)
}

// WithSessionHooks mocks base method.
func (m *MockHookManager) WithSessionHooks(ctx context.Context, sessionID uuid.UUID, work func() error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithSessionHooks", ctx, sessionID, work)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithSessionHooks indicates an expected call of WithSessionHooks.
func (mr *MockHookManagerMockRecorder) WithSessionHooks(ctx, sessionID, work any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithSessionHooks", reflect.TypeOf((*MockHookManager)(nil).WithSessionHooks), ctx, sessionID, work)
}

// WithToolHooks mocks base method.
func (m *MockHookManager) WithToolHooks(ctx context.Context, sessionID, agentID uuid.UUID, toolName string, args map[string]any, work func() (map[string]any, error)) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithToolHooks", ctx, sessionID, agentID, toolName, args, work)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithToolHooks indicates an expected call of WithToolHooks.
func (mr *MockHookManagerMockRecorder) WithToolHooks(ctx, sessionID, agentID, toolName, args, work any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithToolHooks", reflect.TypeOf((*MockHookManager)(nil).WithToolHooks), ctx, sessionID, agentID, toolName, args, work)
}
