// Code generated by MockGen. DO NOT EDIT.
// Source: ../skills/service.go
//
// Generated by this command:
//
//	mockgen -source=../skills/service.go -destination=mock_skill_service.go -package=mocks github.com/denkhaus/gollum/pkg/skills SkillService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	skills "github.com/denkhaus/gollum/pkg/skills"
	gomock "go.uber.org/mock/gomock"
)

// MockSkillService is a mock of SkillService interface.
type MockSkillService struct {
	ctrl     *gomock.Controller
	recorder *MockSkillServiceMockRecorder
	isgomock struct{}
}

// MockSkillServiceMockRecorder is the mock recorder for MockSkillService.
type MockSkillServiceMockRecorder struct {
	mock *MockSkillService
}

// NewMockSkillService creates a new mock instance.
func NewMockSkillService(ctrl *gomock.Controller) *MockSkillService {
	mock := &MockSkillService{ctrl: ctrl}
	mock.recorder = &MockSkillServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillService) EXPECT() *MockSkillServiceMockRecorder {
	return m.recorder
}

// AddSearchPath mocks base method.
func (m *MockSkillService) AddSearchPath(path string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddSearchPath", path)
}

// AddSearchPath indicates an expected call of AddSearchPath.
func (mr *MockSkillServiceMockRecorder) AddSearchPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSearchPath", reflect.TypeOf((*MockSkillService)(nil).AddSearchPath), path)
}

// AddSearchPathAndDiscover mocks base method.
func (m *MockSkillService) AddSearchPathAndDiscover(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSearchPathAndDiscover", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSearchPathAndDiscover indicates an expected call of AddSearchPathAndDiscover.
func (mr *MockSkillServiceMockRecorder) AddSearchPathAndDiscover(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSearchPathAndDiscover", reflect.TypeOf((*MockSkillService)(nil).AddSearchPathAndDiscover), ctx, path)
}

// Discover mocks base method.
func (m *MockSkillService) Discover(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Discover", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Discover indicates an expected call of Discover.
func (mr *MockSkillServiceMockRecorder) Discover(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Discover", reflect.TypeOf((*MockSkillService)(nil).Discover), ctx)
}

// Get mocks base method.
func (m *MockSkillService) Get(name string) (*skills.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(*skills.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSkillServiceMockRecorder) Get(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSkillService)(nil).Get), name)
}

// GetByPath mocks base method.
func (m *MockSkillService) GetByPath(path string) (*skills.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPath", path)
	ret0, _ := ret[0].(*skills.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPath indicates an expected call of GetByPath.
func (mr *MockSkillServiceMockRecorder) GetByPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPath", reflect.TypeOf((*MockSkillService)(nil).GetByPath), path)
}

// GetSearchPaths mocks base method.
func (m *MockSkillService) GetSearchPaths() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSearchPaths")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSearchPaths indicates an expected call of GetSearchPaths.
func (mr *MockSkillServiceMockRecorder) GetSearchPaths() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSearchPaths", reflect.TypeOf((*MockSkillService)(nil).GetSearchPaths))
}

// List mocks base method.
func (m *MockSkillService) List() skills.Skills {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(skills.Skills)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockSkillServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSkillService)(nil).List))
}

// ListByType mocks base method.
func (m *MockSkillService) ListByType(skillType skills.SkillType) skills.Skills {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByType", skillType)
	ret0, _ := ret[0].(skills.Skills)
	return ret0
}

// ListByType indicates an expected call of ListByType.
func (mr *MockSkillServiceMockRecorder) ListByType(skillType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByType", reflect.TypeOf((*MockSkillService)(nil).ListByType), skillType)
}

// ListUserInvocable mocks base method.
func (m *MockSkillService) ListUserInvocable() skills.Skills {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserInvocable")
	ret0, _ := ret[0].(skills.Skills)
	return ret0
}

// ListUserInvocable indicates an expected call of ListUserInvocable.
func (mr *MockSkillServiceMockRecorder) ListUserInvocable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserInvocable", reflect.TypeOf((*MockSkillService)(nil).ListUserInvocable))
}

// Refresh mocks base method.
func (m *MockSkillService) Refresh(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockSkillServiceMockRecorder) Refresh(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockSkillService)(nil).Refresh), ctx)
}

// RemoveSearchPath mocks base method.
func (m *MockSkillService) RemoveSearchPath(path string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveSearchPath", path)
}

// RemoveSearchPath indicates an expected call of RemoveSearchPath.
func (mr *MockSkillServiceMockRecorder) RemoveSearchPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSearchPath", reflect.TypeOf((*MockSkillService)(nil).RemoveSearchPath), path)
}

// Validate mocks base method.
func (m *MockSkillService) Validate(skill *skills.Skill) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", skill)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockSkillServiceMockRecorder) Validate(skill any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockSkillService)(nil).Validate), skill)
}

// ValidateTools mocks base method.
func (m *MockSkillService) ValidateTools(skill *skills.Skill) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTools", skill)
	ret0, _ := ret[0].([]string)
	return ret0
}

// ValidateTools indicates an expected call of ValidateTools.
func (mr *MockSkillServiceMockRecorder) ValidateTools(skill any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTools", reflect.TypeOf((*MockSkillService)(nil).ValidateTools), skill)
}
