// Code generated by MockGen. DO NOT EDIT.
// Source: ../logger/logger.go
//
// Generated by this command:
//
//	mockgen -source=../logger/logger.go -destination=mock_logger_service.go -package=mocks github.com/denkhaus/gollum/pkg/logger LoggerService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	logger "github.com/denkhaus/gollum/pkg/logger"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockLoggerService is a mock of LoggerService interface.
type MockLoggerService struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerServiceMockRecorder
	isgomock struct{}
}

// MockLoggerServiceMockRecorder is the mock recorder for MockLoggerService.
type MockLoggerServiceMockRecorder struct {
	mock *MockLoggerService
}

// NewMockLoggerService creates a new mock instance.
func NewMockLoggerService(ctrl *gomock.Controller) *MockLoggerService {
	mock := &MockLoggerService{ctrl: ctrl}
	mock.recorder = &MockLoggerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoggerService) EXPECT() *MockLoggerServiceMockRecorder {
	return m.recorder
}

// CloseFileLogging mocks base method.
func (m *MockLoggerService) CloseFileLogging() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseFileLogging")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseFileLogging indicates an expected call of CloseFileLogging.
func (mr *MockLoggerServiceMockRecorder) CloseFileLogging() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseFileLogging", reflect.TypeOf((*MockLoggerService)(nil).CloseFileLogging))
}

// Debug mocks base method.
func (m *MockLoggerService) Debug(msg string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerServiceMockRecorder) Debug(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLoggerService)(nil).Debug), varargs...)
}

// Debugf mocks base method.
func (m *MockLoggerService) Debugf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockLoggerServiceMockRecorder) Debugf(template any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*MockLoggerService)(nil).Debugf), varargs...)
}

// EnableFileLogging mocks base method.
func (m *MockLoggerService) EnableFileLogging(gollumDir string, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableFileLogging", gollumDir, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableFileLogging indicates an expected call of EnableFileLogging.
func (mr *MockLoggerServiceMockRecorder) EnableFileLogging(gollumDir, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableFileLogging", reflect.TypeOf((*MockLoggerService)(nil).EnableFileLogging), gollumDir, sessionID)
}

// Error mocks base method.
func (m *MockLoggerService) Error(msg string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerServiceMockRecorder) Error(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLoggerService)(nil).Error), varargs...)
}

// Errorf mocks base method.
func (m *MockLoggerService) Errorf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockLoggerServiceMockRecorder) Errorf(template any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockLoggerService)(nil).Errorf), varargs...)
}

// Flush mocks base method.
func (m *MockLoggerService) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockLoggerServiceMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockLoggerService)(nil).Flush))
}

// GetLogStats mocks base method.
func (m *MockLoggerService) GetLogStats() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogStats")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetLogStats indicates an expected call of GetLogStats.
func (mr *MockLoggerServiceMockRecorder) GetLogStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogStats", reflect.TypeOf((*MockLoggerService)(nil).GetLogStats))
}

// GetLogger mocks base method.
func (m *MockLoggerService) GetLogger() *zap.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogger")
	ret0, _ := ret[0].(*zap.Logger)
	return ret0
}

// GetLogger indicates an expected call of GetLogger.
func (mr *MockLoggerServiceMockRecorder) GetLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogger", reflect.TypeOf((*MockLoggerService)(nil).GetLogger))
}

// GetLogs mocks base method.
func (m *MockLoggerService) GetLogs(filter logger.LogFilter) []logger.LogEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogs", filter)
	ret0, _ := ret[0].([]logger.LogEntry)
	return ret0
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockLoggerServiceMockRecorder) GetLogs(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockLoggerService)(nil).GetLogs), filter)
}

// Info mocks base method.
func (m *MockLoggerService) Info(msg string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerServiceMockRecorder) Info(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLoggerService)(nil).Info), varargs...)
}

// Infof mocks base method.
func (m *MockLoggerService) Infof(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockLoggerServiceMockRecorder) Infof(template any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockLoggerService)(nil).Infof), varargs...)
}

// IsTUIMode mocks base method.
func (m *MockLoggerService) IsTUIMode() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTUIMode")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTUIMode indicates an expected call of IsTUIMode.
func (mr *MockLoggerServiceMockRecorder) IsTUIMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTUIMode", reflect.TypeOf((*MockLoggerService)(nil).IsTUIMode))
}

// SetTUIMode mocks base method.
func (m *MockLoggerService) SetTUIMode(enabled bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTUIMode", enabled)
}

// SetTUIMode indicates an expected call of SetTUIMode.
func (mr *MockLoggerServiceMockRecorder) SetTUIMode(enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTUIMode", reflect.TypeOf((*MockLoggerService)(nil).SetTUIMode), enabled)
}

// Warn mocks base method.
func (m *MockLoggerService) Warn(msg string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerServiceMockRecorder) Warn(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLoggerService)(nil).Warn), varargs...)
}

// Warnf mocks base method.
func (m *MockLoggerService) Warnf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf.
func (mr *MockLoggerServiceMockRecorder) Warnf(template any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockLoggerService)(nil).Warnf), varargs...)
}
