// Code generated by MockGen. DO NOT EDIT.
// Source: ../prompt/manager/manager.go
//
// Generated by this command:
//
//	mockgen -source=../prompt/manager/manager.go -destination=mock_prompt_manager.go -package=mocks github.com/denkhaus/gollum/pkg/prompt/manager PromptManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	prompt "github.com/denkhaus/gollum/pkg/prompt"
	store "github.com/denkhaus/gollum/pkg/prompt/store"
	gomock "go.uber.org/mock/gomock"
)

// MockPromptManager is a mock of PromptManager interface.
type MockPromptManager struct {
	ctrl     *gomock.Controller
	recorder *MockPromptManagerMockRecorder
	isgomock struct{}
}

// MockPromptManagerMockRecorder is the mock recorder for MockPromptManager.
type MockPromptManagerMockRecorder struct {
	mock *MockPromptManager
}

// NewMockPromptManager creates a new mock instance.
func NewMockPromptManager(ctrl *gomock.Controller) *MockPromptManager {
	mock := &MockPromptManager{ctrl: ctrl}
	mock.recorder = &MockPromptManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromptManager) EXPECT() *MockPromptManagerMockRecorder {
	return m.recorder
}

// DeletePrompt mocks base method.
func (m *MockPromptManager) DeletePrompt(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrompt", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrompt indicates an expected call of DeletePrompt.
func (mr *MockPromptManagerMockRecorder) DeletePrompt(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrompt", reflect.TypeOf((*MockPromptManager)(nil).DeletePrompt), ctx, id)
}

// GetCompacterPrompt mocks base method.
func (m *MockPromptManager) GetCompacterPrompt(data any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompacterPrompt", data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompacterPrompt indicates an expected call of GetCompacterPrompt.
func (mr *MockPromptManagerMockRecorder) GetCompacterPrompt(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompacterPrompt", reflect.TypeOf((*MockPromptManager)(nil).GetCompacterPrompt), data)
}

// GetPromptByID mocks base method.
func (m *MockPromptManager) GetPromptByID(ctx context.Context, id string) (*prompt.Prompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromptByID", ctx, id)
	ret0, _ := ret[0].(*prompt.Prompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromptByID indicates an expected call of GetPromptByID.
func (mr *MockPromptManagerMockRecorder) GetPromptByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromptByID", reflect.TypeOf((*MockPromptManager)(nil).GetPromptByID), ctx, id)
}

// GetPromptWithContext mocks base method.
func (m *MockPromptManager) GetPromptWithContext(ctx context.Context, id string, renderCtx *prompt.RenderContext) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromptWithContext", ctx, id, renderCtx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromptWithContext indicates an expected call of GetPromptWithContext.
func (mr *MockPromptManagerMockRecorder) GetPromptWithContext(ctx, id, renderCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromptWithContext", reflect.TypeOf((*MockPromptManager)(nil).GetPromptWithContext), ctx, id, renderCtx)
}

// GetStore mocks base method.
func (m *MockPromptManager) GetStore() store.PromptStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStore")
	ret0, _ := ret[0].(store.PromptStore)
	return ret0
}

// GetStore indicates an expected call of GetStore.
func (mr *MockPromptManagerMockRecorder) GetStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockPromptManager)(nil).GetStore))
}

// GetSubagentPrompt mocks base method.
func (m *MockPromptManager) GetSubagentPrompt(role, description string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubagentPrompt", role, description)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubagentPrompt indicates an expected call of GetSubagentPrompt.
func (mr *MockPromptManagerMockRecorder) GetSubagentPrompt(role, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubagentPrompt", reflect.TypeOf((*MockPromptManager)(nil).GetSubagentPrompt), role, description)
}

// GetSupervisorPrompt mocks base method.
func (m *MockPromptManager) GetSupervisorPrompt() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupervisorPrompt")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupervisorPrompt indicates an expected call of GetSupervisorPrompt.
func (mr *MockPromptManagerMockRecorder) GetSupervisorPrompt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupervisorPrompt", reflect.TypeOf((*MockPromptManager)(nil).GetSupervisorPrompt))
}

// GetSystemPrompt mocks base method.
func (m *MockPromptManager) GetSystemPrompt() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemPrompt")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemPrompt indicates an expected call of GetSystemPrompt.
func (mr *MockPromptManagerMockRecorder) GetSystemPrompt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemPrompt", reflect.TypeOf((*MockPromptManager)(nil).GetSystemPrompt))
}

// GetWorkspaceContext mocks base method.
func (m *MockPromptManager) GetWorkspaceContext() *prompt.WorkspaceContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceContext")
	ret0, _ := ret[0].(*prompt.WorkspaceContext)
	return ret0
}

// GetWorkspaceContext indicates an expected call of GetWorkspaceContext.
func (mr *MockPromptManagerMockRecorder) GetWorkspaceContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceContext", reflect.TypeOf((*MockPromptManager)(nil).GetWorkspaceContext))
}

// ListPrompts mocks base method.
func (m *MockPromptManager) ListPrompts(ctx context.Context, filter *prompt.ListFilter) ([]*prompt.Prompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPrompts", ctx, filter)
	ret0, _ := ret[0].([]*prompt.Prompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPrompts indicates an expected call of ListPrompts.
func (mr *MockPromptManagerMockRecorder) ListPrompts(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPrompts", reflect.TypeOf((*MockPromptManager)(nil).ListPrompts), ctx, filter)
}

// RenderPrompt mocks base method.
func (m *MockPromptManager) RenderPrompt(ctx context.Context, p *prompt.Prompt, renderCtx *prompt.RenderContext) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderPrompt", ctx, p, renderCtx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderPrompt indicates an expected call of RenderPrompt.
func (mr *MockPromptManagerMockRecorder) RenderPrompt(ctx, p, renderCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderPrompt", reflect.TypeOf((*MockPromptManager)(nil).RenderPrompt), ctx, p, renderCtx)
}

// SetPrompt mocks base method.
func (m *MockPromptManager) SetPrompt(ctx context.Context, id, content, name string) (*prompt.Prompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrompt", ctx, id, content, name)
	ret0, _ := ret[0].(*prompt.Prompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPrompt indicates an expected call of SetPrompt.
func (mr *MockPromptManagerMockRecorder) SetPrompt(ctx, id, content, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrompt", reflect.TypeOf((*MockPromptManager)(nil).SetPrompt), ctx, id, content, name)
}

// SetWorkspaceContext mocks base method.
func (m *MockPromptManager) SetWorkspaceContext(ctx *prompt.WorkspaceContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWorkspaceContext", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWorkspaceContext indicates an expected call of SetWorkspaceContext.
func (mr *MockPromptManagerMockRecorder) SetWorkspaceContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkspaceContext", reflect.TypeOf((*MockPromptManager)(nil).SetWorkspaceContext), ctx)
}

// UpdateWorkspaceFromSkillService mocks base method.
func (m *MockPromptManager) UpdateWorkspaceFromSkillService(ctx context.Context, currentPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkspaceFromSkillService", ctx, currentPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkspaceFromSkillService indicates an expected call of UpdateWorkspaceFromSkillService.
func (mr *MockPromptManagerMockRecorder) UpdateWorkspaceFromSkillService(ctx, currentPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkspaceFromSkillService", reflect.TypeOf((*MockPromptManager)(nil).UpdateWorkspaceFromSkillService), ctx, currentPath)
}
