// Code generated by MockGen. DO NOT EDIT.
// Source: ../prompt/manager.go
//
// Generated by this command:
//
//	mockgen -source=../prompt/manager.go -destination=mock_prompt_manager.go -package=mocks github.com/denkhaus/gollum/pkg/prompt PromptManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPromptManager is a mock of PromptManager interface.
type MockPromptManager struct {
	ctrl     *gomock.Controller
	recorder *MockPromptManagerMockRecorder
	isgomock struct{}
}

// MockPromptManagerMockRecorder is the mock recorder for MockPromptManager.
type MockPromptManagerMockRecorder struct {
	mock *MockPromptManager
}

// NewMockPromptManager creates a new mock instance.
func NewMockPromptManager(ctrl *gomock.Controller) *MockPromptManager {
	mock := &MockPromptManager{ctrl: ctrl}
	mock.recorder = &MockPromptManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromptManager) EXPECT() *MockPromptManagerMockRecorder {
	return m.recorder
}

// GetCompacterPrompt mocks base method.
func (m *MockPromptManager) GetCompacterPrompt(data any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompacterPrompt", data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompacterPrompt indicates an expected call of GetCompacterPrompt.
func (mr *MockPromptManagerMockRecorder) GetCompacterPrompt(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompacterPrompt", reflect.TypeOf((*MockPromptManager)(nil).GetCompacterPrompt), data)
}

// GetSubagentPrompt mocks base method.
func (m *MockPromptManager) GetSubagentPrompt(role, description string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubagentPrompt", role, description)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubagentPrompt indicates an expected call of GetSubagentPrompt.
func (mr *MockPromptManagerMockRecorder) GetSubagentPrompt(role, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubagentPrompt", reflect.TypeOf((*MockPromptManager)(nil).GetSubagentPrompt), role, description)
}

// GetSupervisorPrompt mocks base method.
func (m *MockPromptManager) GetSupervisorPrompt() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupervisorPrompt")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupervisorPrompt indicates an expected call of GetSupervisorPrompt.
func (mr *MockPromptManagerMockRecorder) GetSupervisorPrompt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupervisorPrompt", reflect.TypeOf((*MockPromptManager)(nil).GetSupervisorPrompt))
}

// GetSystemPrompt mocks base method.
func (m *MockPromptManager) GetSystemPrompt() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemPrompt")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemPrompt indicates an expected call of GetSystemPrompt.
func (mr *MockPromptManagerMockRecorder) GetSystemPrompt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemPrompt", reflect.TypeOf((*MockPromptManager)(nil).GetSystemPrompt))
}
