// Code generated by MockGen. DO NOT EDIT.
// Source: ../workspace/service.go
//
// Generated by this command:
//
//	mockgen -source=../workspace/service.go -destination=mock_workspace_service.go -package=mocks github.com/denkhaus/gollum/pkg/workspace Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	workspace "github.com/denkhaus/gollum/pkg/workspace"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddToHistory mocks base method.
func (m *MockService) AddToHistory(path string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddToHistory", path)
}

// AddToHistory indicates an expected call of AddToHistory.
func (mr *MockServiceMockRecorder) AddToHistory(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToHistory", reflect.TypeOf((*MockService)(nil).AddToHistory), path)
}

// ClearHistory mocks base method.
func (m *MockService) ClearHistory() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearHistory")
}

// ClearHistory indicates an expected call of ClearHistory.
func (mr *MockServiceMockRecorder) ClearHistory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearHistory", reflect.TypeOf((*MockService)(nil).ClearHistory))
}

// GetCurrentWorkspace mocks base method.
func (m *MockService) GetCurrentWorkspace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentWorkspace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCurrentWorkspace indicates an expected call of GetCurrentWorkspace.
func (mr *MockServiceMockRecorder) GetCurrentWorkspace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentWorkspace", reflect.TypeOf((*MockService)(nil).GetCurrentWorkspace))
}

// GetWorkspaceContext mocks base method.
func (m *MockService) GetWorkspaceContext() *workspace.WorkspaceContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceContext")
	ret0, _ := ret[0].(*workspace.WorkspaceContext)
	return ret0
}

// GetWorkspaceContext indicates an expected call of GetWorkspaceContext.
func (mr *MockServiceMockRecorder) GetWorkspaceContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceContext", reflect.TypeOf((*MockService)(nil).GetWorkspaceContext))
}

// GetWorkspaceHistory mocks base method.
func (m *MockService) GetWorkspaceHistory() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceHistory")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetWorkspaceHistory indicates an expected call of GetWorkspaceHistory.
func (mr *MockServiceMockRecorder) GetWorkspaceHistory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceHistory", reflect.TypeOf((*MockService)(nil).GetWorkspaceHistory))
}

// SetCurrentWorkspace mocks base method.
func (m *MockService) SetCurrentWorkspace(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCurrentWorkspace", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCurrentWorkspace indicates an expected call of SetCurrentWorkspace.
func (mr *MockServiceMockRecorder) SetCurrentWorkspace(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCurrentWorkspace", reflect.TypeOf((*MockService)(nil).SetCurrentWorkspace), path)
}
