// Code generated by MockGen. DO NOT EDIT.
// Source: ../shared/agent.go
//
// Generated by this command:
//
//	mockgen -source=../shared/agent.go -destination=mock_agent.go -package=mocks github.com/denkhaus/gollum/pkg/shared Agent
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	shared "github.com/denkhaus/gollum/pkg/shared"
	uuid "github.com/google/uuid"
	gollem "github.com/m-mizutani/gollem"
	gomock "go.uber.org/mock/gomock"
)

// MockAgent is a mock of Agent interface.
type MockAgent struct {
	ctrl     *gomock.Controller
	recorder *MockAgentMockRecorder
	isgomock struct{}
}

// MockAgentMockRecorder is the mock recorder for MockAgent.
type MockAgentMockRecorder struct {
	mock *MockAgent
}

// NewMockAgent creates a new mock instance.
func NewMockAgent(ctrl *gomock.Controller) *MockAgent {
	mock := &MockAgent{ctrl: ctrl}
	mock.recorder = &MockAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgent) EXPECT() *MockAgentMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockAgent) Execute(ctx context.Context, input ...gollem.Input) (*gollem.ExecuteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range input {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Execute", varargs...)
	ret0, _ := ret[0].(*gollem.ExecuteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockAgentMockRecorder) Execute(ctx any, input ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, input...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockAgent)(nil).Execute), varargs...)
}

// GetConfig mocks base method.
func (m *MockAgent) GetConfig() *shared.AgentConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(*shared.AgentConfig)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockAgentMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockAgent)(nil).GetConfig))
}

// GetID mocks base method.
func (m *MockAgent) GetID() uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockAgentMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockAgent)(nil).GetID))
}

// GetMessageHistory mocks base method.
func (m *MockAgent) GetMessageHistory(ctx context.Context) (*gollem.History, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageHistory", ctx)
	ret0, _ := ret[0].(*gollem.History)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageHistory indicates an expected call of GetMessageHistory.
func (mr *MockAgentMockRecorder) GetMessageHistory(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageHistory", reflect.TypeOf((*MockAgent)(nil).GetMessageHistory), ctx)
}

// Session mocks base method.
func (m *MockAgent) Session() gollem.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session")
	ret0, _ := ret[0].(gollem.Session)
	return ret0
}

// Session indicates an expected call of Session.
func (mr *MockAgentMockRecorder) Session() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockAgent)(nil).Session))
}

// UpdateHistory mocks base method.
func (m *MockAgent) UpdateHistory(ctx context.Context, modifier func(*gollem.History) (*gollem.History, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHistory", ctx, modifier)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHistory indicates an expected call of UpdateHistory.
func (mr *MockAgentMockRecorder) UpdateHistory(ctx, modifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHistory", reflect.TypeOf((*MockAgent)(nil).UpdateHistory), ctx, modifier)
}

// UpdateSystemPrompt mocks base method.
func (m *MockAgent) UpdateSystemPrompt(ctx context.Context, newPrompt string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSystemPrompt", ctx, newPrompt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSystemPrompt indicates an expected call of UpdateSystemPrompt.
func (mr *MockAgentMockRecorder) UpdateSystemPrompt(ctx, newPrompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSystemPrompt", reflect.TypeOf((*MockAgent)(nil).UpdateSystemPrompt), ctx, newPrompt)
}
