// Code generated by MockGen. DO NOT EDIT.
// Source: ../tools/agent_execution_helper.go
//
// Generated by this command:
//
//	mockgen -source=../tools/agent_execution_helper.go -destination=mock_agent_execution_helper.go -package=mocks github.com/denkhaus/gollum/pkg/tools AgentExecutionHelper
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	shared "github.com/denkhaus/gollum/pkg/shared"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentExecutionHelper is a mock of AgentExecutionHelper interface.
type MockAgentExecutionHelper struct {
	ctrl     *gomock.Controller
	recorder *MockAgentExecutionHelperMockRecorder
	isgomock struct{}
}

// MockAgentExecutionHelperMockRecorder is the mock recorder for MockAgentExecutionHelper.
type MockAgentExecutionHelperMockRecorder struct {
	mock *MockAgentExecutionHelper
}

// NewMockAgentExecutionHelper creates a new mock instance.
func NewMockAgentExecutionHelper(ctrl *gomock.Controller) *MockAgentExecutionHelper {
	mock := &MockAgentExecutionHelper{ctrl: ctrl}
	mock.recorder = &MockAgentExecutionHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentExecutionHelper) EXPECT() *MockAgentExecutionHelperMockRecorder {
	return m.recorder
}

// ErrorResponse mocks base method.
func (m *MockAgentExecutionHelper) ErrorResponse(errMsg string) map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ErrorResponse", errMsg)
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// ErrorResponse indicates an expected call of ErrorResponse.
func (mr *MockAgentExecutionHelperMockRecorder) ErrorResponse(errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorResponse", reflect.TypeOf((*MockAgentExecutionHelper)(nil).ErrorResponse), errMsg)
}

// ExecuteInBackground mocks base method.
func (m *MockAgentExecutionHelper) ExecuteInBackground(ctx context.Context, agent shared.Agent, prompt string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ExecuteInBackground", ctx, agent, prompt)
}

// ExecuteInBackground indicates an expected call of ExecuteInBackground.
func (mr *MockAgentExecutionHelperMockRecorder) ExecuteInBackground(ctx, agent, prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteInBackground", reflect.TypeOf((*MockAgentExecutionHelper)(nil).ExecuteInBackground), ctx, agent, prompt)
}

// ExecuteSynchronously mocks base method.
func (m *MockAgentExecutionHelper) ExecuteSynchronously(ctx context.Context, agent shared.Agent, prompt string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteSynchronously", ctx, agent, prompt)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteSynchronously indicates an expected call of ExecuteSynchronously.
func (mr *MockAgentExecutionHelperMockRecorder) ExecuteSynchronously(ctx, agent, prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteSynchronously", reflect.TypeOf((*MockAgentExecutionHelper)(nil).ExecuteSynchronously), ctx, agent, prompt)
}

// SuccessResponseAsync mocks base method.
func (m *MockAgentExecutionHelper) SuccessResponseAsync(agentID uuid.UUID, role, description string) map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuccessResponseAsync", agentID, role, description)
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// SuccessResponseAsync indicates an expected call of SuccessResponseAsync.
func (mr *MockAgentExecutionHelperMockRecorder) SuccessResponseAsync(agentID, role, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuccessResponseAsync", reflect.TypeOf((*MockAgentExecutionHelper)(nil).SuccessResponseAsync), agentID, role, description)
}

// SuccessResponseResumeAsync mocks base method.
func (m *MockAgentExecutionHelper) SuccessResponseResumeAsync(agentID uuid.UUID, role, description string) map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuccessResponseResumeAsync", agentID, role, description)
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// SuccessResponseResumeAsync indicates an expected call of SuccessResponseResumeAsync.
func (mr *MockAgentExecutionHelperMockRecorder) SuccessResponseResumeAsync(agentID, role, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuccessResponseResumeAsync", reflect.TypeOf((*MockAgentExecutionHelper)(nil).SuccessResponseResumeAsync), agentID, role, description)
}

// SuccessResponseSync mocks base method.
func (m *MockAgentExecutionHelper) SuccessResponseSync(agentID uuid.UUID, response string) map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuccessResponseSync", agentID, response)
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// SuccessResponseSync indicates an expected call of SuccessResponseSync.
func (mr *MockAgentExecutionHelperMockRecorder) SuccessResponseSync(agentID, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuccessResponseSync", reflect.TypeOf((*MockAgentExecutionHelper)(nil).SuccessResponseSync), agentID, response)
}
