// Code generated by MockGen. DO NOT EDIT.
// Source: ../diff/provider.go
//
// Generated by this command:
//
//	mockgen -source=../diff/provider.go -destination=mock_diff_provider.go -package=mocks github.com/denkhaus/gollum/pkg/diff Provider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// FormatCompact mocks base method.
func (m *MockProvider) FormatCompact(diff string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatCompact", diff)
	ret0, _ := ret[0].(string)
	return ret0
}

// FormatCompact indicates an expected call of FormatCompact.
func (mr *MockProviderMockRecorder) FormatCompact(diff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatCompact", reflect.TypeOf((*MockProvider)(nil).FormatCompact), diff)
}

// FormatForDisplay mocks base method.
func (m *MockProvider) FormatForDisplay(diff string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatForDisplay", diff)
	ret0, _ := ret[0].(string)
	return ret0
}

// FormatForDisplay indicates an expected call of FormatForDisplay.
func (mr *MockProviderMockRecorder) FormatForDisplay(diff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatForDisplay", reflect.TypeOf((*MockProvider)(nil).FormatForDisplay), diff)
}

// GenerateDiff mocks base method.
func (m *MockProvider) GenerateDiff(oldPath, newPath, oldContent, newContent string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDiff", oldPath, newPath, oldContent, newContent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDiff indicates an expected call of GenerateDiff.
func (mr *MockProviderMockRecorder) GenerateDiff(oldPath, newPath, oldContent, newContent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDiff", reflect.TypeOf((*MockProvider)(nil).GenerateDiff), oldPath, newPath, oldContent, newContent)
}

// GenerateDiffForNewFile mocks base method.
func (m *MockProvider) GenerateDiffForNewFile(path, content string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDiffForNewFile", path, content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDiffForNewFile indicates an expected call of GenerateDiffForNewFile.
func (mr *MockProviderMockRecorder) GenerateDiffForNewFile(path, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDiffForNewFile", reflect.TypeOf((*MockProvider)(nil).GenerateDiffForNewFile), path, content)
}
