// Code generated by MockGen. DO NOT EDIT.
// Source: ../workspace/service.go
//
// Generated by this command:
//
//	mockgen -source=../workspace/service.go -destination=mock_workspace_service.go -package=mocks github.com/denkhaus/gollum/pkg/workspace Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetCurrentWorkspace mocks base method.
func (m *MockService) GetCurrentWorkspace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentWorkspace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCurrentWorkspace indicates an expected call of GetCurrentWorkspace.
func (mr *MockServiceMockRecorder) GetCurrentWorkspace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentWorkspace", reflect.TypeOf((*MockService)(nil).GetCurrentWorkspace))
}

// GetWorkspaceHistory mocks base method.
func (m *MockService) GetWorkspaceHistory() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceHistory")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetWorkspaceHistory indicates an expected call of GetWorkspaceHistory.
func (mr *MockServiceMockRecorder) GetWorkspaceHistory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceHistory", reflect.TypeOf((*MockService)(nil).GetWorkspaceHistory))
}
