// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/m-mizutani/gollem (interfaces: Session)
//
// Generated by this command:
//
//	mockgen -destination=mock_session.go -package=mocks github.com/m-mizutani/gollem Session
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gollem "github.com/m-mizutani/gollem"
	gomock "go.uber.org/mock/gomock"
)

// MockSession is a mock of Session interface.
type MockSession struct {
	ctrl     *gomock.Controller
	recorder *MockSessionMockRecorder
	isgomock struct{}
}

// MockSessionMockRecorder is the mock recorder for MockSession.
type MockSessionMockRecorder struct {
	mock *MockSession
}

// NewMockSession creates a new mock instance.
func NewMockSession(ctrl *gomock.Controller) *MockSession {
	mock := &MockSession{ctrl: ctrl}
	mock.recorder = &MockSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSession) EXPECT() *MockSessionMockRecorder {
	return m.recorder
}

// AppendHistory mocks base method.
func (m *MockSession) AppendHistory(arg0 *gollem.History) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendHistory", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendHistory indicates an expected call of AppendHistory.
func (mr *MockSessionMockRecorder) AppendHistory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendHistory", reflect.TypeOf((*MockSession)(nil).AppendHistory), arg0)
}

// CountToken mocks base method.
func (m *MockSession) CountToken(ctx context.Context, input ...gollem.Input) (int, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range input {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CountToken", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountToken indicates an expected call of CountToken.
func (mr *MockSessionMockRecorder) CountToken(ctx any, input ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, input...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountToken", reflect.TypeOf((*MockSession)(nil).CountToken), varargs...)
}

// GenerateContent mocks base method.
func (m *MockSession) GenerateContent(ctx context.Context, input ...gollem.Input) (*gollem.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range input {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GenerateContent", varargs...)
	ret0, _ := ret[0].(*gollem.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateContent indicates an expected call of GenerateContent.
func (mr *MockSessionMockRecorder) GenerateContent(ctx any, input ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, input...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateContent", reflect.TypeOf((*MockSession)(nil).GenerateContent), varargs...)
}

// GenerateStream mocks base method.
func (m *MockSession) GenerateStream(ctx context.Context, input ...gollem.Input) (<-chan *gollem.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range input {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GenerateStream", varargs...)
	ret0, _ := ret[0].(<-chan *gollem.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateStream indicates an expected call of GenerateStream.
func (mr *MockSessionMockRecorder) GenerateStream(ctx any, input ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, input...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateStream", reflect.TypeOf((*MockSession)(nil).GenerateStream), varargs...)
}

// History mocks base method.
func (m *MockSession) History() (*gollem.History, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History")
	ret0, _ := ret[0].(*gollem.History)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockSessionMockRecorder) History() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockSession)(nil).History))
}
