// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/config/service.go
//
// Generated by this command:
//
//	mockgen -source=pkg/config/service.go -destination=pkg/mocks/mock_config_service.go -package=mocks github.com/denkhaus/gollum/pkg/config ConfigService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	config "github.com/denkhaus/gollum/pkg/config"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigService is a mock of ConfigService interface.
type MockConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockConfigServiceMockRecorder
	isgomock struct{}
}

// MockConfigServiceMockRecorder is the mock recorder for MockConfigService.
type MockConfigServiceMockRecorder struct {
	mock *MockConfigService
}

// NewMockConfigService creates a new mock instance.
func NewMockConfigService(ctrl *gomock.Controller) *MockConfigService {
	mock := &MockConfigService{ctrl: ctrl}
	mock.recorder = &MockConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigService) EXPECT() *MockConfigServiceMockRecorder {
	return m.recorder
}

// GetAgentLimits mocks base method.
func (m *MockConfigService) GetAgentLimits() *config.AgentLimitsConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentLimits")
	ret0, _ := ret[0].(*config.AgentLimitsConfig)
	return ret0
}

// GetAgentLimits indicates an expected call of GetAgentLimits.
func (mr *MockConfigServiceMockRecorder) GetAgentLimits() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentLimits", reflect.TypeOf((*MockConfigService)(nil).GetAgentLimits))
}

// GetAnthropicConfig mocks base method.
func (m *MockConfigService) GetAnthropicConfig() *config.AnthropicConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnthropicConfig")
	ret0, _ := ret[0].(*config.AnthropicConfig)
	return ret0
}

// GetAnthropicConfig indicates an expected call of GetAnthropicConfig.
func (mr *MockConfigServiceMockRecorder) GetAnthropicConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnthropicConfig", reflect.TypeOf((*MockConfigService)(nil).GetAnthropicConfig))
}

// GetBashConfig mocks base method.
func (m *MockConfigService) GetBashConfig() *config.BashConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBashConfig")
	ret0, _ := ret[0].(*config.BashConfig)
	return ret0
}

// GetBashConfig indicates an expected call of GetBashConfig.
func (mr *MockConfigServiceMockRecorder) GetBashConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBashConfig", reflect.TypeOf((*MockConfigService)(nil).GetBashConfig))
}

// GetFilesConfig mocks base method.
func (m *MockConfigService) GetFilesConfig() *config.FilesConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilesConfig")
	ret0, _ := ret[0].(*config.FilesConfig)
	return ret0
}

// GetFilesConfig indicates an expected call of GetFilesConfig.
func (mr *MockConfigServiceMockRecorder) GetFilesConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilesConfig", reflect.TypeOf((*MockConfigService)(nil).GetFilesConfig))
}

// GetGeminiConfig mocks base method.
func (m *MockConfigService) GetGeminiConfig() *config.GeminiConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeminiConfig")
	ret0, _ := ret[0].(*config.GeminiConfig)
	return ret0
}

// GetGeminiConfig indicates an expected call of GetGeminiConfig.
func (mr *MockConfigServiceMockRecorder) GetGeminiConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeminiConfig", reflect.TypeOf((*MockConfigService)(nil).GetGeminiConfig))
}

// GetHooksConfig mocks base method.
func (m *MockConfigService) GetHooksConfig() *config.HooksConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHooksConfig")
	ret0, _ := ret[0].(*config.HooksConfig)
	return ret0
}

// GetHooksConfig indicates an expected call of GetHooksConfig.
func (mr *MockConfigServiceMockRecorder) GetHooksConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHooksConfig", reflect.TypeOf((*MockConfigService)(nil).GetHooksConfig))
}

// GetLogLevel mocks base method.
func (m *MockConfigService) GetLogLevel() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogLevel")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLogLevel indicates an expected call of GetLogLevel.
func (mr *MockConfigServiceMockRecorder) GetLogLevel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogLevel", reflect.TypeOf((*MockConfigService)(nil).GetLogLevel))
}

// GetLoggingConfig mocks base method.
func (m *MockConfigService) GetLoggingConfig() *config.LoggingConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoggingConfig")
	ret0, _ := ret[0].(*config.LoggingConfig)
	return ret0
}

// GetLoggingConfig indicates an expected call of GetLoggingConfig.
func (mr *MockConfigServiceMockRecorder) GetLoggingConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoggingConfig", reflect.TypeOf((*MockConfigService)(nil).GetLoggingConfig))
}

// GetOpenAIConfig mocks base method.
func (m *MockConfigService) GetOpenAIConfig() *config.OpenAIConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenAIConfig")
	ret0, _ := ret[0].(*config.OpenAIConfig)
	return ret0
}

// GetOpenAIConfig indicates an expected call of GetOpenAIConfig.
func (mr *MockConfigServiceMockRecorder) GetOpenAIConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenAIConfig", reflect.TypeOf((*MockConfigService)(nil).GetOpenAIConfig))
}

// GetPromptOptimizerConfig mocks base method.
func (m *MockConfigService) GetPromptOptimizerConfig() *config.PromptOptimizerConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromptOptimizerConfig")
	ret0, _ := ret[0].(*config.PromptOptimizerConfig)
	return ret0
}

// GetPromptOptimizerConfig indicates an expected call of GetPromptOptimizerConfig.
func (mr *MockConfigServiceMockRecorder) GetPromptOptimizerConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromptOptimizerConfig", reflect.TypeOf((*MockConfigService)(nil).GetPromptOptimizerConfig))
}

// GetPromptStoreConfig mocks base method.
func (m *MockConfigService) GetPromptStoreConfig() *config.PromptStoreConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromptStoreConfig")
	ret0, _ := ret[0].(*config.PromptStoreConfig)
	return ret0
}

// GetPromptStoreConfig indicates an expected call of GetPromptStoreConfig.
func (mr *MockConfigServiceMockRecorder) GetPromptStoreConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromptStoreConfig", reflect.TypeOf((*MockConfigService)(nil).GetPromptStoreConfig))
}

// IsDevMode mocks base method.
func (m *MockConfigService) IsDevMode() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDevMode")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDevMode indicates an expected call of IsDevMode.
func (mr *MockConfigServiceMockRecorder) IsDevMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDevMode", reflect.TypeOf((*MockConfigService)(nil).IsDevMode))
}
