// Code generated by MockGen. DO NOT EDIT.
// Source: ../prompt/store/store.go
//
// Generated by this command:
//
//	mockgen -source=../prompt/store/store.go -destination=mock_store.go -package=mocks github.com/denkhaus/gollum/pkg/prompt/store PromptStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	prompt "github.com/denkhaus/gollum/pkg/prompt"
	store "github.com/denkhaus/gollum/pkg/prompt/store"
	gomock "go.uber.org/mock/gomock"
)

// MockPromptStore is a mock of PromptStore interface.
type MockPromptStore struct {
	ctrl     *gomock.Controller
	recorder *MockPromptStoreMockRecorder
	isgomock struct{}
}

// MockPromptStoreMockRecorder is the mock recorder for MockPromptStore.
type MockPromptStoreMockRecorder struct {
	mock *MockPromptStore
}

// NewMockPromptStore creates a new mock instance.
func NewMockPromptStore(ctrl *gomock.Controller) *MockPromptStore {
	mock := &MockPromptStore{ctrl: ctrl}
	mock.recorder = &MockPromptStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromptStore) EXPECT() *MockPromptStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockPromptStore) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPromptStoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPromptStore)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockPromptStore) Exists(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockPromptStoreMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockPromptStore)(nil).Exists), ctx, id)
}

// List mocks base method.
func (m *MockPromptStore) List(ctx context.Context, filter *store.ListFilter) ([]*prompt.Prompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*prompt.Prompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPromptStoreMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPromptStore)(nil).List), ctx, filter)
}

// ListTags mocks base method.
func (m *MockPromptStore) ListTags(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockPromptStoreMockRecorder) ListTags(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockPromptStore)(nil).ListTags), ctx)
}

// ListVersions mocks base method.
func (m *MockPromptStore) ListVersions(ctx context.Context, baseID string) ([]*prompt.Prompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVersions", ctx, baseID)
	ret0, _ := ret[0].([]*prompt.Prompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVersions indicates an expected call of ListVersions.
func (mr *MockPromptStoreMockRecorder) ListVersions(ctx, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVersions", reflect.TypeOf((*MockPromptStore)(nil).ListVersions), ctx, baseID)
}

// Load mocks base method.
func (m *MockPromptStore) Load(ctx context.Context, id string) (*prompt.Prompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, id)
	ret0, _ := ret[0].(*prompt.Prompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockPromptStoreMockRecorder) Load(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockPromptStore)(nil).Load), ctx, id)
}

// ResolveAlias mocks base method.
func (m *MockPromptStore) ResolveAlias(ctx context.Context, id string) (*prompt.Prompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAlias", ctx, id)
	ret0, _ := ret[0].(*prompt.Prompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAlias indicates an expected call of ResolveAlias.
func (mr *MockPromptStoreMockRecorder) ResolveAlias(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAlias", reflect.TypeOf((*MockPromptStore)(nil).ResolveAlias), ctx, id)
}

// SaveNewVersion mocks base method.
func (m *MockPromptStore) SaveNewVersion(ctx context.Context, baseID, content, name string) (*prompt.Prompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNewVersion", ctx, baseID, content, name)
	ret0, _ := ret[0].(*prompt.Prompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveNewVersion indicates an expected call of SaveNewVersion.
func (mr *MockPromptStoreMockRecorder) SaveNewVersion(ctx, baseID, content, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNewVersion", reflect.TypeOf((*MockPromptStore)(nil).SaveNewVersion), ctx, baseID, content, name)
}

// SetLatestAlias mocks base method.
func (m *MockPromptStore) SetLatestAlias(ctx context.Context, baseID, versionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLatestAlias", ctx, baseID, versionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLatestAlias indicates an expected call of SetLatestAlias.
func (mr *MockPromptStoreMockRecorder) SetLatestAlias(ctx, baseID, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLatestAlias", reflect.TypeOf((*MockPromptStore)(nil).SetLatestAlias), ctx, baseID, versionID)
}
