// Code generated by MockGen. DO NOT EDIT.
// Source: tui/model.go
//
// Generated by this command:
//
//	mockgen -source=tui/model.go -destination=tui/model_mock.go -package=tui github.com/denkhaus/gollum/pkg/tui AgentExecutor
//

// Package tui is a generated GoMock package.
package tui
