// Code generated by MockGen. DO NOT EDIT.
// Source: tui/model.go
//
// Generated by this command:
//
//	mockgen -source=tui/model.go -destination=tui/model_mock.go -package=tui github.com/denkhaus/gollum/pkg/tui AgentExecutor
//

// Package tui is a generated GoMock package.
package tui

import (
	context "context"
	reflect "reflect"

	gollem "github.com/m-mizutani/gollem"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentExecutor is a mock of AgentExecutor interface.
type MockAgentExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockAgentExecutorMockRecorder
	isgomock struct{}
}

// MockAgentExecutorMockRecorder is the mock recorder for MockAgentExecutor.
type MockAgentExecutorMockRecorder struct {
	mock *MockAgentExecutor
}

// NewMockAgentExecutor creates a new mock instance.
func NewMockAgentExecutor(ctrl *gomock.Controller) *MockAgentExecutor {
	mock := &MockAgentExecutor{ctrl: ctrl}
	mock.recorder = &MockAgentExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentExecutor) EXPECT() *MockAgentExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockAgentExecutor) Execute(ctx context.Context, input string) (*gollem.ExecuteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*gollem.ExecuteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockAgentExecutorMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockAgentExecutor)(nil).Execute), ctx, input)
}
