// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/flows/registry/service.go
//
// Generated by this command:
//
//	mockgen -source=pkg/flows/registry/service.go -destination=pkg/flows/registry/registry_mock.go -package=registry github.com/denkhaus/gollum/pkg/flows/registry FlowRegistry
//

// Package registry is a generated GoMock package.
package registry

import (
	reflect "reflect"

	flows "github.com/denkhaus/gollum/pkg/flows"
	gomock "go.uber.org/mock/gomock"
)

// MockFlowRegistry is a mock of FlowRegistry interface.
type MockFlowRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockFlowRegistryMockRecorder
	isgomock struct{}
}

// MockFlowRegistryMockRecorder is the mock recorder for MockFlowRegistry.
type MockFlowRegistryMockRecorder struct {
	mock *MockFlowRegistry
}

// NewMockFlowRegistry creates a new mock instance.
func NewMockFlowRegistry(ctrl *gomock.Controller) *MockFlowRegistry {
	mock := &MockFlowRegistry{ctrl: ctrl}
	mock.recorder = &MockFlowRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowRegistry) EXPECT() *MockFlowRegistryMockRecorder {
	return m.recorder
}

// GetFlow mocks base method.
func (m *MockFlowRegistry) GetFlow(ref string) (*flows.Flow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlow", ref)
	ret0, _ := ret[0].(*flows.Flow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlow indicates an expected call of GetFlow.
func (mr *MockFlowRegistryMockRecorder) GetFlow(ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlow", reflect.TypeOf((*MockFlowRegistry)(nil).GetFlow), ref)
}

// GetFlowInfo mocks base method.
func (m *MockFlowRegistry) GetFlowInfo(name string) (*FlowInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlowInfo", name)
	ret0, _ := ret[0].(*FlowInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlowInfo indicates an expected call of GetFlowInfo.
func (mr *MockFlowRegistryMockRecorder) GetFlowInfo(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlowInfo", reflect.TypeOf((*MockFlowRegistry)(nil).GetFlowInfo), name)
}

// ListFlows mocks base method.
func (m *MockFlowRegistry) ListFlows() ([]*FlowInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFlows")
	ret0, _ := ret[0].([]*FlowInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFlows indicates an expected call of ListFlows.
func (mr *MockFlowRegistryMockRecorder) ListFlows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFlows", reflect.TypeOf((*MockFlowRegistry)(nil).ListFlows))
}

// Register mocks base method.
func (m *MockFlowRegistry) Register(name string, flow *flows.Flow) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", name, flow)
}

// Register indicates an expected call of Register.
func (mr *MockFlowRegistryMockRecorder) Register(name, flow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockFlowRegistry)(nil).Register), name, flow)
}
