// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/flows/executor/executor.go
//
// Generated by this command:
//
//	mockgen -source=pkg/flows/executor/executor.go -destination=pkg/flows/executor/mock.go -package=executor github.com/denkhaus/gollum/pkg/flows/executor FlowExecutorService,FlowExecutorInstance
//

// Package executor is a generated GoMock package.
package executor

import (
	reflect "reflect"

	flows "github.com/denkhaus/gollum/pkg/flows"
	shared "github.com/denkhaus/gollum/pkg/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockFlowExecutorService is a mock of FlowExecutorService interface.
type MockFlowExecutorService struct {
	ctrl     *gomock.Controller
	recorder *MockFlowExecutorServiceMockRecorder
	isgomock struct{}
}

// MockFlowExecutorServiceMockRecorder is the mock recorder for MockFlowExecutorService.
type MockFlowExecutorServiceMockRecorder struct {
	mock *MockFlowExecutorService
}

// NewMockFlowExecutorService creates a new mock instance.
func NewMockFlowExecutorService(ctrl *gomock.Controller) *MockFlowExecutorService {
	mock := &MockFlowExecutorService{ctrl: ctrl}
	mock.recorder = &MockFlowExecutorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowExecutorService) EXPECT() *MockFlowExecutorServiceMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockFlowExecutorService) New(flow *flows.Flow) shared.FlowExecutorInstance {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", flow)
	ret0, _ := ret[0].(shared.FlowExecutorInstance)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockFlowExecutorServiceMockRecorder) New(flow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockFlowExecutorService)(nil).New), flow)
}
