// Code generated by MockGen. DO NOT EDIT.
// Source: flows/executor/executor.go
//
// Generated by this command:
//
//	mockgen -source=flows/executor/executor.go -destination=flows/executor/mock.go -package=executor github.com/denkhaus/gollum/pkg/flows/executor FlowExecutorService
//

// Package executor is a generated GoMock package.
package executor

import (
	reflect "reflect"

	flows "github.com/denkhaus/gollum/pkg/flows"
	gomock "go.uber.org/mock/gomock"
)

// MockFlowExecutorInstance is a mock of FlowExecutorInstance interface.
type MockFlowExecutorInstance struct {
	ctrl     *gomock.Controller
	recorder *MockFlowExecutorInstanceMockRecorder
	isgomock struct{}
}

// MockFlowExecutorInstanceMockRecorder is the mock recorder for MockFlowExecutorInstance.
type MockFlowExecutorInstanceMockRecorder struct {
	mock *MockFlowExecutorInstance
}

// NewMockFlowExecutorInstance creates a new mock instance.
func NewMockFlowExecutorInstance(ctrl *gomock.Controller) *MockFlowExecutorInstance {
	mock := &MockFlowExecutorInstance{ctrl: ctrl}
	mock.recorder = &MockFlowExecutorInstanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowExecutorInstance) EXPECT() *MockFlowExecutorInstanceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockFlowExecutorInstance) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockFlowExecutorInstanceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFlowExecutorInstance)(nil).Close))
}

// GetContext mocks base method.
func (m *MockFlowExecutorInstance) GetContext() ExecutionContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContext")
	ret0, _ := ret[0].(ExecutionContext)
	return ret0
}

// GetContext indicates an expected call of GetContext.
func (mr *MockFlowExecutorInstanceMockRecorder) GetContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContext", reflect.TypeOf((*MockFlowExecutorInstance)(nil).GetContext))
}

// Run mocks base method.
func (m *MockFlowExecutorInstance) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockFlowExecutorInstanceMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockFlowExecutorInstance)(nil).Run))
}

// SetInput mocks base method.
func (m *MockFlowExecutorInstance) SetInput(vals map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInput", vals)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetInput indicates an expected call of SetInput.
func (mr *MockFlowExecutorInstanceMockRecorder) SetInput(vals any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInput", reflect.TypeOf((*MockFlowExecutorInstance)(nil).SetInput), vals)
}

// Validate mocks base method.
func (m *MockFlowExecutorInstance) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockFlowExecutorInstanceMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockFlowExecutorInstance)(nil).Validate))
}

// MockFlowExecutorService is a mock of FlowExecutorService interface.
type MockFlowExecutorService struct {
	ctrl     *gomock.Controller
	recorder *MockFlowExecutorServiceMockRecorder
	isgomock struct{}
}

// MockFlowExecutorServiceMockRecorder is the mock recorder for MockFlowExecutorService.
type MockFlowExecutorServiceMockRecorder struct {
	mock *MockFlowExecutorService
}

// NewMockFlowExecutorService creates a new mock instance.
func NewMockFlowExecutorService(ctrl *gomock.Controller) *MockFlowExecutorService {
	mock := &MockFlowExecutorService{ctrl: ctrl}
	mock.recorder = &MockFlowExecutorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowExecutorService) EXPECT() *MockFlowExecutorServiceMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockFlowExecutorService) New(flow *flows.Flow) FlowExecutorInstance {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", flow)
	ret0, _ := ret[0].(FlowExecutorInstance)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockFlowExecutorServiceMockRecorder) New(flow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockFlowExecutorService)(nil).New), flow)
}
